### ISSUE TITLE
秒站

### ISSUE THREAD

**Issue by gebangfeng** [xx025/carrot#107]
周报通
https://zhoubaotong.com/zh
![ad4c02e29b0687861032d03803f6676c_](https://user-images.githubusercontent.com/56078492/227481184-96af5df9-8354-4399-8535-6cd19e4b5cb4.png)
![69ba8e949bb6a2b88f4890f539e62973_](https://user-images.githubusercontent.com/56078492/227481218-6a4fd6bb-323c-4f1a-acab-9fa895633ad4.png)

**Comment by xx025** [comment]
一已添加
