### ISSUE TITLE
挂了一个网站

### ISSUE THREAD

**Issue by caipeizhi** [xx025/carrot#112]
https://poe.com/

**Comment by xx025** [comment]
> https://poe.com/
> 

这个事国外的网站，需要代理，他要是不提供chat服务了可以告诉我，

刚刚我测试是可以打开的

**Comment by xx025** [comment]
![day20230325084300](https://user-images.githubusercontent.com/71559822/227668703-8366acd2-99ca-47c1-97be-7a7c01861cb2.gif)
已测试，可以使用，可以尝试换一些代理；或者使用其他网站
