### ISSUE TITLE
域名替换申请

### ISSUE THREAD

**Issue by shadow2kk** [xx025/carrot#131]
因昨天受到批量请求攻击，额度消耗较快，故此加入限制。
现已解决，再次解除访问限制。
另因GFW，烦请大佬替换一下域名后缀，让国内用户可以访问。
https://www.ftcl.site/（被墙） -> https://www.ftcl.store/

**Comment by xx025** [comment]
换掉了，但是需要知道和理解的是，因为站点过多，将`受限使用` 的站点进行了折叠

关于受限使用：包括使用次数受限制、需要key、当时时间间隔限制也会包括在内

还望理解
