### ISSUE TITLE
申请收录 Chat35.com

### ISSUE THREAD

**Issue by cinycherls** [xx025/carrot#135]
一个我个人一直在使用的ChatGPT镜像网站 Chat35.com  很稳定，还可以通过邀请获得次数，我反正是没花过钱。

**Comment by xx025** [comment]
> 一个我个人一直在使用的ChatGPT镜像网站 Chat35.com  很稳定，还可以通过邀请获得次数，我反正是没花过钱。


收到，但是，对这类使用受限的站点，暂时会放在叠掉分组，稍后会更新

有其他合理的建议可以告诉我
