### ISSUE TITLE
求推荐位，可使用GPT-4的网站

### ISSUE THREAD

**Issue by yitd** [xx025/carrot#138]
http://www.tdchat.vip/
GPT-4资格稀缺且使用昂贵，但是仍然开启了每人每天可免费使用3次的权限。
![a](https://i.imgtg.com/2023/03/28/j9BcU.png)

**Comment by yitd** [comment]
原网址tdchat.com已被封，请保存并使用以下入口网址：http://www.tdchat.nethttp://www.tdchat.viphttp://www.tdchat.imhttp://www.tdchat.de商城地址是：http://pay.tdchat.net/

**Comment by yitd** [comment]
> 稍后会标注 `可尝试GPT4`

更新辛苦了，赞赏了点薄礼支持下你

**Comment by xx025** [comment]
> > 稍后会标注 `可尝试GPT4`
> 
> 更新辛苦了，赞赏了点薄礼支持下你

非常感谢🙏🙏🙏

如果你想推广自己的网站，可以考虑一下那个广告位置，今天晚上会换一周的广告

**Comment by yitd** [comment]
> 
暂时不用啦，谢谢，后续有需要的话会找你的
