### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by aska1031** [xx025/carrot#140]
哈喽，我是网站开发者，除了gpt和dall-e，还基于openai的接口开发了4个工具，每天会有免费1000k tokens共享额度。

https://chat.topsearcher.top/

**Comment by jkm199** [comment]
https://bot.d8.pw
每天赠送免费次数，超过需要充值

**Comment by xx025** [comment]
收到，我对1k 没什么概念，但是我稍稍测试了一下消耗很快

希望能理解，因为站点比较多，我会对其标上受限制标记，稍后会更新

**Comment by aska1031** [comment]
好的。因为是共享的，所以你看到的一次消耗量是网站多人同时使用时的消耗量，是会比较快

**Comment by xx025** [comment]
> 哈喽，我是网站开发者，除了gpt和dall-e，还基于openai的接口开发了4个工具，每天会有免费1000k tokens共享额度。
> 
> https://chat.topsearcher.top/



> https://bot.d8.pw 每天赠送免费次数，超过需要充值

均已添加
