### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by danicaStarR** [xx025/carrot#158]
- https://chat1.binjie.site:7777 有“联网模式”
- http://openmao.com/#/index b站up主建立

**Comment by xx025** [comment]
> * https://chat1.binjie.site:7777 有“联网模式”
这个网站的  https://chat8.yqcloud.top/ 这个子域名已经在列表里面了

> * http://openmao.com/#/index b站up主建立
这个站点我目前无论是否代理上网都还是不能打开；之前被曾被放在列表里，后来被列在失效站点中了
