### ISSUE TITLE
请求纳入站点

### ISSUE THREAD

**Issue by CNSeniorious000** [xx025/carrot#180]
可以加入我创建的一个国内可用的免费ChatGPT镜像站吗

[chat.bnu120.space](https://chat.bnu120.space/)

**Comment by xx025** [comment]
客气了，加上了

**Comment by CNSeniorious000** [comment]
那个链接现在墙了😂可以放上我的新域名吗 [chat0.bnu120.space](https://chat0.bnu120.space/) 麻烦了

**Comment by xx025** [comment]
> chat.bnu120.space

🆗，已更新
