### ISSUE TITLE
新站提交：柯基乐趣。

### ISSUE THREAD

**Issue by Liwu253874** [xx025/carrot#181]
网址是：https://www.kejilequ.com
寓意让每个人都能享受（ChatGPT）科技带来的乐趣。
并不是大多数那种使用开源项目代码搭建的第三方ChatGPT工具，只需要通过一个Email地址注册，不需要API Key，就可以使用ChatGPT对话的功能。目前只支持3.5 。现在是纯免费的，注册就送110条对话资格，对于大多数体验的人来说足够多了。（毕竟很多第三方也就能免费聊两条）。

**Comment by xx025** [comment]
已添加
