### ISSUE TITLE
[添加站点] chatgpt-api-web

### ISSUE THREAD

**Issue by heimoshuiyu** [xx025/carrot#191]
**网址**

```
https://heimoshuiyu.github.io/chatgpt-api-web/?key=fakekey&api=https%3A%2F%2F3lio5ooiekcn3gxx6du2jf5wzq0mudmm.lambda-url.us-east-1.on.aws%2F&mode=fetch
```
**网站类型**
- [x] ChatGPT站点
- [ ] 其他

**是否需要国际网络(可选)**
- [x] 否
- [ ] 是

**使用方式(可选)**

- [x] 免费无限制 
- [x] 可使用自定义 key
- [ ] 登录使用，登陆后无限制
- [ ] 需要key 使用
- [ ] 有限使用次数，需要付费(赞赏、捐赠、赞助)使用

**Comment by xx025** [comment]
感谢分享，已添加
