### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by ZhuLei886** [xx025/carrot#194]
**网址**

```
https://chat.zhuleixx.top/
```

**网站类型**
- [x] ChatGPT站点
- [ ] 其他

**是否需要国际网络(可选)**
- [x] 否
- [ ] 是

**ico 路径(可选)**

```
https://chat.zhuleixx.top/favicon.svg
```

**使用方式(可选)**

- [x] 免费无限制 
- [ ] 登录使用，登陆后无限制
- [ ] 需要key 使用
- [ ] 有限使用次数，需要付费(赞赏、捐赠、赞助)使用

**Comment by xx025** [comment]
🆗，已添加
