### ISSUE TITLE
[修改站点] 

### ISSUE THREAD

**Issue by binjie09** [xx025/carrot#196]
**网址**
我是binjie.site的开发者 binjie.site指向国内服务器所以访问极快，但肉身在国内的我被查了，责令关停，希望能换成国外的服务器 首次访问慢：https://chat23.yqcloud.top 
```
https://chat23.yqcloud.top
```

**网站类型**
- [x] ChatGPT站点
- [ ] 其他

**是否需要国际网络(可选)**
- [x] 否
- [ ] 是

**使用方式(可选)**

- [x] 免费无限制 
- [ ] 登录使用，登陆后无限制
- [ ] 需要key 使用
- [ ] 有限使用次数，需要付费(赞赏、捐赠、赞助)使用

**Comment by svjack** [comment]
有可以通过赞助的方式获得持续维护的商用版的方法吗？我想购买，谢谢。

**Comment by xx025** [comment]
收到，已更新

**Comment by ENIAC1729** [comment]
谢谢站长,chargpt对ip太苛刻了,我老是进不去,多亏了您的网站

**Comment by xnyjb** [comment]
比较担心站长免费可以维持多久，希望可以付费使用。

**Comment by ENIAC1729** [comment]
我感觉大部分人还是都有梯子的

**Comment by hetangx** [comment]
大哥，感谢你的网站，帮大忙了！能否捐助

**Comment by liang75013** [comment]
希望能长期使用，可以捐助，太难了 ~

**Comment by binjie09** [comment]
@liang75013 @hetangx @xnyjb @svjack 一起回复下，可捐助，网站扫码打赏即可，最高只支持3元，免费能维持很久，国内商用被网信办摁住了，正在沟通，请先使用免费服务。有其他事可以邮件联系 github@binjie.site 每日回。

**Comment by 520HZM** [comment]
你好，我发现一个问题，edge浏览器侧边栏不能添加该网页，我认为侧边栏对于使用该软件来说比较重要，希望大佬可以看一下。

**Comment by CarlDemetri008** [comment]
已支持3元，大佬给力

**Comment by lxg20000101** [comment]
已捐助给大佬了。这个网站我在公司可用，在自己的手机和家里电脑不可用，提示“好像出错了，请稍后再试”

**Comment by danielyyj** [comment]
已捐助，帮助非常大

**Comment by kuangzhiyu37** [comment]
阔落一杯，感谢大佬，希望一直用下去

**Comment by SonicEver** [comment]
买了瓶水，我希望能有所帮助
如果流量贵我觉得可以搞成注册付费使用

**Comment by fengtaishao** [comment]
怎么联系您qq或者微信，请私聊我下，谢谢

**Comment by Ericcaman** [comment]
刚刚买了瓶水，天天都在用，非常感谢

**Comment by doctordragon666** [comment]
给大佬打钱啦，大佬的网站真的很好，有些收费网站就是加次数，真不行。
能给个联系吗

**Comment by Kyzgel** [comment]
大佬，现在为什么不能联网了啊

**Comment by MyMorty001** [comment]
感谢！！！

**Comment by nonozzzzz** [comment]
进不去耶

**Comment by wx-1014** [comment]
现在怎么弄，不让用了
