### ISSUE TITLE
不建议url需要经过网站跳转

### ISSUE THREAD

**Issue by yitd** [xx025/carrot#200]
你使用的是cloudflare，第一会影响速度，第二有的地区的运营商屏蔽了cloudflare
![s](https://i.imgtg.com/2023/04/11/85G1q.png)

**Comment by xx025** [comment]
感谢对此提出的意见

这么做的原因是这样的。因为最初并没有这么做，有人copy文档、发布网站，进行噶韭菜行为，非常不喜欢这种操作，所以有此操作。另外，gh能访问cf肯定不成问题。

当然我也希望找到好用的短链接api、网站logo api还有实惠的图床。

Chatgpt目前在国内有很大程度上被定为非法律允许的服务，且行且珍惜。

**Comment by yitd** [comment]
原网址tdchat.com已被封，GPT-4已上线，请保存新的TDChat入口网址：http://tdchat.de（地址发布页-收藏不迷路）http://tdchat.im（地址发布页-收藏不迷路）http://tdchat.nethttp://tdchat.vip商城地址是：http://pays.tdchat.de/
