### ISSUE TITLE
推荐一个超好用的ChatGPT镜像，可联网+150多种prompt提示词模板 可选模型！！！

### ISSUE THREAD

**Issue by Wtcityx** [xx025/carrot#206]
https://filedf12d74756b0.v4.h5sys.cn/openai/chat
![image](https://user-images.githubusercontent.com/95459923/231538774-5c173e9c-797f-45e6-86d4-db0c065109cc.png)

**Comment by xx025** [comment]
这个是输入自己的账号么？

**Comment by Wtcityx** [comment]
不是哦，输入自己的邮箱和自设的密码就可以

**Comment by xx025** [comment]
Ok 已添加
