### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by 740400019** [xx025/carrot#209]
**网址**

```
http://a.aizh.app/
```

**网站类型**
- [x] ChatGPT站点
- [ ] 其他

**是否需要国际网络(可选)**
- [x] 否
- [ ] 是

**ico 路径(可选)**

```
https://camo.githubusercontent.com/ca54604e6873602da61c4dedda5c4f58a4c7453a22b61fb7655c75e7408efbf4/68747470733a2f2f73742e616935352e63632f66617669636f6e2f7971636c6f75642e746f702e737667
```

**使用方式(可选)**

- [] 免费无限制 
- [x] 登录使用，登陆后无限制
- [ ] 需要key 使用
- [x] 有限使用次数，需要付费(赞赏、捐赠、赞助)使用

**Comment by xx025** [comment]
🆗，已添加
