### ISSUE TITLE
中文prompt 论坛（2000+prompt）每日更新

### ISSUE THREAD

**Issue by dreammis** [xx025/carrot#211]
**网址**

```
https://bbs.allaitools.cn
```

**网站类型**

- [] ChatGPT站点
- [x] 其他

2000+好用prompt，免费分享
写作，编程，营销，seo等等

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [] 😄 免费使用
- [x] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**ico 路径(可选)**

```

```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加到`妙站`分组
