### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by clearcodecn** [xx025/carrot#212]
**网址**

```
https://x-sms.cn
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用
- [] 🔑 免费使用，需要登录或密码
- [x] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
https://x-sms.cn/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
暂时没有这种销售chat账号这种分组，我已记录，后期如有分组计划会添加
