### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by liuzhiguo630** [xx025/carrot#216]
**网址**

```
aHR0cHM6Ly9saWFvYm90cy5jb20=
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用
- [ ] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [x] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
aHR0cHM6Ly9saWFvYm90cy5jb20vZmF2aWNvbi5pY28=
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

# 特色
不搞月付，采用按量付费模式，￥0.02/1000 Token，聊多少充多少。UI 和体验与官网接近，免注册打开就用，赠送 5000 Token。
![CleanShot 2023-04-14 at 13 43 28@2x](https://user-images.githubusercontent.com/9815635/231951710-889e2cc5-1957-4971-b487-a287c8391221.jpg)

**Comment by xx025** [comment]
🆗，已添加
