### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by SoBison** [xx025/carrot#218]
**网址**

```
https://apps.apple.com/app/id1671426850
```

**网站类型**

- [x] ChatGPT站点
- [x] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用
- [ ] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [x] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

iOS  软件

**Comment by xx025** [comment]
🆗，已添加
