### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by freebr** [xx025/carrot#220]
**网址**

```
1.公众号：广州欧讯服科技有限公司（关注后可直接发消息对话）
2. https://freebr.cn/oxf/chat （需通过微信登录，仅支持在微信手机端或电脑端中打开）
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用
- [x] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
https://freebr.cn/oxf/chat/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
