### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by ahgaoshan** [xx025/carrot#222]
**网址**

```
https://chat.hywwwlove.top/?code=QVv5
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用
- [ ] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加

**Comment by ahgaoshan** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
