### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by mengjian-github** [xx025/carrot#226]
**网址**

```
https://www.ailab.fit/
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用
- [ ] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**Comment by xx025** [comment]
🆗，已添加
