### ISSUE TITLE
[添加站点] 开放猫【新网址】

### ISSUE THREAD

**Issue by fendouai** [xx025/carrot#232]
**网址**

```
https://openmao.panchuang.net/
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用
- [ ] 🔑 免费使用，需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**ico 路径(可选)**

```
https://openmao.panchuang.net/assets/logo-7073afb7.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

原网址因DNS解析问题，更新为新网址。

**Comment by xx025** [comment]
🆗，已更新
