### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by wk3758** [xx025/carrot#235]
**网址**

```
aigpt.one
```
**免费使用，可导出**

> 请尽量描述清楚，各行方便

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
