### ISSUE TITLE
[添加站点] chatgpt国内可用站点

### ISSUE THREAD

**Issue by jjjj2023** [xx025/carrot#238]
**网址**

```公众号访问 锦翼科技   使用
``公众号访问 锦翼科技   使用
网页H5访问下面网址 同步更新 赠5条
http://ai.jy2.com.cn/web

```
**网站简介或说明**

>``公众号访问 锦翼科技   使用
网页H5访问下面网址 同步更新 赠5条
http://ai.jy2.com.cn/web

**网站类型**

ChatGPT站点

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ √] 😄 限时免费使用(打开即可用无限制)
- [√ ] 🔑 需要登录或密码
- [ √] 🤑 付费使用
- [ √] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```


**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
测试好像 web 页面无法正常使用

![image](https://user-images.githubusercontent.com/71559822/232403522-b5f0e3d4-9cea-4dac-9bf6-d76755c7b99f.png)
