### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by wuguokai** [xx025/carrot#240]
**网址**

```
https://chat.wuguokai.cn
```
**网站简介或说明**

> 使用GPT-3.5接口，不限制使用次数，不限制输入与回复长度，支持上下文，国内CDN加速

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形

```
https://chat.wuguokai.cn/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by wuguokai** [comment]
抱歉，搞错了，这个网站已经在列表中了。
这个网站使用GPT-3.5接口，不限制使用次数，不限制输入与回复长度，支持上下文，国内CDN加速
可以加星哦~谢谢！

**Comment by xx025** [comment]
OK，已更新

**Comment by hrh0804** [comment]
nice，bro!!!
