### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by 123seven** [xx025/carrot#241]
**网址**

```
主：https://smartchat.unknownbyte.com/
备：https://smartchat.yihezu.cn/
```
**网站简介或说明**

> 为您提供更加个性化、智能化的聊天服务。

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(25次/天、可自备KEY无限制使用)
- [x] 🔑 需要登录或密码
- [ ] 🤑 付费使用
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
```
https://smartchat.unknownbyte.com/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已更新
