### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by Wtcity22** [xx025/carrot#243]
**网址**

```
https://filedf12d74756b0.v4.h5sys.cn/openai/chat
```
**网站简介或说明**
全网最还原|免费ChatGPT站点，支持联网插件以及150多种prompt模板!

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🔑 需要登录或密码
- [ ] 🤑 付费使用
- [ ] 🎁 付费使用，体验次数

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
