### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by StellaBae** [xx025/carrot#248]
**网址**

```
https://toolbuilder.ai/
```
**网站简介或说明**

> Toolbuilder 是无需编码即可创建和探索 '自定义 AI tools' 的平台
> 免费

**网站类型**

- [ ] ChatGPT站点
- [x] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://toolbuilder.ai/favicon.png
```

**是否需要国际网络(可选)**

- [ ] 否
- [x] 是

**Comment by xx025** [comment]
🆗，已添加
