### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by liyanan666** [xx025/carrot#249]
**网址**

```
https://www.weijiwangluo.com/talk
```
**网站简介或说明**

付费+体验次数
基于gpt-3.5-turbo引擎封装的网站,通过输入文本，输出相应的回答，实现智能聊天的功能

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [x ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://cdn.weijiwangluo.com/chat/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
