### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by 239573049** [xx025/carrot#253]
**网址**

```
https://open666.cn/
```
**网站简介或说明**

> SK集成AI，支持ChatGpt 3.5和图片AI，登录免费使用每天50次，付费无限使用，使用SK集成，支持更多AI

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🤑 付费使用 或 🔑 需要登录或密码
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://open666.cn/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
