### ISSUE TITLE
[反馈] 链接问题

### ISSUE THREAD

**Issue by xjzh123** [xx025/carrot#262]
添加广告很正常，然而对链接使用你自己的网站进行跳转，而且跳转链接上看不出目标URL，这是为了防止爬虫盗取链接吗？还是为了跟踪用户呢？如果可以的话，我希望能够采用明文链接的方式。

**Comment by xx025** [comment]
可能有好几个原因，
1. 防止盗链
2. 防止站点被批量扫描

最初这么做的原因是有人复刻网站和仓库推广知识星球

如果执意要求的话，还需要等些时间对当前的渲染程序做些改动，要是站点有要求可以明文链接

**Comment by xjzh123** [comment]
感谢回复，我只是一个普通的路人，这是合情合理的，很抱歉作出了恶意揣测。您维护也辛苦了。
