### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by Hansonwong47** [xx025/carrot#270]
网址： Chaosu.vip

问题：網站打不開，請求移除。

**Comment by xx025** [comment]
可以打开啊
![image](https://user-images.githubusercontent.com/71559822/233345026-7f079358-df25-4d21-a2bd-561cec1c3168.png)

![image](https://user-images.githubusercontent.com/71559822/233345245-cd7e5961-3353-43d2-b53c-80c7489d575f.png)

没问题啊
