### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by dnaisok** [xx025/carrot#272]
**网址**

```
https://chat.789ai.top//
```
**网站简介或说明**

> chatgpt,不用梯子，国内访问
> 加微信送次数
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [ ] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://openaiapi-site.azureedge.net/public-assets/d/a6dfcc50a2/favicon.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
