### ISSUE TITLE
https://x.aiseo.lat

### ISSUE THREAD

**Issue by webpon** [xx025/carrot#273]
**网址**

```
https://x.aiseo.lat/
```
**网站简介或说明**
免费 

**网站类型**

ChatGPT站点

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

😄 免费使用(打开即可用无限制)

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
>https://f1.nbai.live/

🆗，已添加
