### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by ChangeYu0229** [xx025/carrot#274]
**网址**

```
https://ssw9noe1h6.feishu.cn/wiki/wikcn59pPXfAiF1ONajdPzvhA9d
```
**网站简介或说明**

「AI 知识库」 永久免费更新，帮助新手从0到1了解AI

**网站类型**

- [] ChatGPT站点
- [x ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://cdn.discordapp.com/attachments/1093344032178049065/1098779276255449260/logo.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
