### ISSUE TITLE
[添加站点] chat.fdkang.top

### ISSUE THREAD

**Issue by fdkang** [xx025/carrot#275]
**网址**

```
chat.fdkang.top
```
**网站简介或说明**

> 请尽量描述清楚，各行方便
> 会给据使用方式分配权重，如: 免费> （付费+体验次数）> 付费 

**网站类型**

- [x] ChatGPT站点

**使用方式**

- [x] 😄 免费使用(打开即可用无限制)

**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
🆗，已添加

**Comment by fdkang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
