### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by movefreely** [xx025/carrot#285]
**网址**

```
http://chat.cutim.top/
```
**网站简介或说明**

> 免费的GPT国内使用网站，未见任何收费，只有首页有一个赞赏码
> 国内可访问，界面模板为开源的 ChatGPT-web 
> 界面干净，在有信息输入之后没有任何干扰

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://chat.cutim.top/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
