### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by clayboby** [xx025/carrot#288]
**网址**

```
https://www.vivi-chat.com/#/chat
```
**网站简介或说明**

> GPT3.5+GPT4，付费API，准备做最大的AI平台，长期稳定，正经服务
> 十五次免费，后续公众号出送3天卡会动，一直都会有活动，欢迎白嫖和推广。

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://www.vivi-chat.com/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [] 是

**Comment by xx025** [comment]
🆗，已添加

**Comment by xx025** [comment]
> 请帮忙修改网址为：https://chat.zhenbs.com/ 网站简介修改为：
> 
> 微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验 每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送 公众号还有各种福利，实现3.5和4的使用
> 
> 非常感谢🙏

请精简一下 10个字以内

**Comment by clayboby** [comment]
> > 请帮忙修改网址为：https://chat.zhenbs.com/ 网站简介修改为：
> > 微信登录后，每天都免费用，注册就送GPT4试用。也可游客体验 每邀请一个人增加一次GPT4的使用次数，外加送GPT3五次和余额赠送 公众号还有各种福利，实现3.5和4的使用
> > 非常感谢🙏
> 
> 请精简一下 10个字左右

好的

3每天用, 分享可无限免费用gpt4
