### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by elevenTrue** [xx025/carrot#298]
**网址**

```
https://gpt-link.com/
```
**网站简介或说明**

> 新注册用户送免费体验次数
> 每日签到可获取免费次数
> 支持付费获取次数
> 微信登录

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [] 😄 免费使用(打开即可用无限制)
- [x] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://cdn.cblink.net/aiyaaa/ai-yaaa-logo.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
