### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by caizhichao** [xx025/carrot#303]
网址： https://gpt.xcbl.cc/

问题：<img width="679" alt="image" src="https://user-images.githubusercontent.com/25865457/233833826-5db30a12-b3e8-4d5b-9aaf-8af5e9da4560.png">

**Comment by Byted4nce** [comment]
> 网址：https://gpt.xcbl.cc/
> 
> 问题：<img alt="图像" width="679" src="https://user-images.githubusercontent.com/25865457/233833826-5db30a12-b3e8-4d5b-9aaf-8af5e9da4560.png">

您好，请刷新页面试试，我这边一切正常。
