### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by ZYB14** [xx025/carrot#305]
**网址**

```
https://chat1.orcle.tech/
```
**网站简介或说明**
稳定，免费，不限次数，无需国际网络
> 请尽量描述清楚，各行方便
> 会给据使用方式分配权重，如: 免费> （付费+体验次数）> 付费 

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://camo.githubusercontent.com/98df50a1bb8ace14c8eb488188b41ca969b5c828e52b6bdad73835f109fc14c2/68747470733a2f2f73742e616935352e63632f66617669636f6e2f61736b6d652e6d6f6d2e69636f
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
