### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by TermsofService11** [xx025/carrot#308]
**网址**

```
https://1.1gpt.uk/
```
**网站简介或说明**

> GPT免费使用，密码：586-481-521A
> 目前开放ChatGPT 3.5 turbo
> GPT-4 申请中

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🤑 付费使用 或 🔑 需要登录或密码
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://www.w3schools.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
