### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by williamwoodhq** [xx025/carrot#323]
**网址**

```
https://www.promptboom.com/
```
**网站简介或说明**

> 无需登录，即可访问
> 免费

**网站类型**

- [x] ChatGPT站点

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)

**网站图标-路径(可选)**
> 正方形 那种

```
https://www.promptboom.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
