### ISSUE TITLE
这个站点是否有人知道！？[反馈] 

### ISSUE THREAD

**Issue by go-2021** [xx025/carrot#325]
网址： ？？

页面很好看，但是不知道网址，有没有知道的，说一下。

![IMG_1633](https://user-images.githubusercontent.com/8136217/234147357-7a6a055e-30cd-4bf9-b137-3345905904f6.PNG)

**Comment by xx025** [comment]
图片顶部有网址

**Comment by go-2021** [comment]
那个是录屏软件的网址，我看了
