### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by honestyallan** [xx025/carrot#327]
**网址**

```
https://xinchain.ai/
```
**网站简介或说明**

> 每天免费使用十次> 邀请好友注册获取免费次数 > 付费 

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**使用方式**

> 请选择一项网站模式，如方便，请尽量选填此项

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🤑 付费使用 或 🔑 需要登录或密码
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://xinchain.ai/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
