### ISSUE TITLE
[添加站点] chatgpt.789ai.top

### ISSUE THREAD

**Issue by dnaisok** [xx025/carrot#342]
**网址**

```
chatgpt.789ai.top
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 国内直接访问，注册送次数，有AI绘图
> 体验次数，付费

- [ ] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> [正方形 那种]

```
http://chatgpt.789ai.top/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
网址不能打开
