### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by huanfeng123** [xx025/carrot#343]
**网址**

```
https://gpt.gpt0.icu/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****
免费使用无需登录，可体验在线上传ppt文档，和ai在线搜索
> 请尽量描述清楚，各行方便
> 会给据使用方式分配权重，如: 免费> （付费+体验次数）> 付费 

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
