### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by zwc4228986** [xx025/carrot#347]
网址： https://chat.douresources.com/

问题：增加AI绘图，聊天免费，绘图只需要看广告

**Comment by 781797330** [comment]
主网址：https://ai.pp2pdf.com/  备用1：http://easy-ai.ink  备用2：http://easyai.ink

gpt3.5 免费的 不需要注册,支持上下文对话.
还支持 Midjourney V5 版本、快图模式、历史创作、创作衍生关联。

**Comment by xx025** [comment]
🆗，已更新

> 网址： https://chat.douresources.com/
> 
> 问题：增加AI绘图，聊天免费，绘图只需要看广告
