### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by huxngmail** [xx025/carrot#359]
**网址**

```
https://gpt6.fun
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

免费使用，没有次数限制，网站长期稳定运行，需要关注公众号获取授权码

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://camo.githubusercontent.com/6b19424ef7b853a069accd5421a742a5e01f2192c07af76598e8ba339c981d46/68747470733a2f2f73742e616935352e63632f66617669636f6e2f64656661756c742d636861746770742d66617669636f6e2e737667
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
