### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by CNSeniorious000** [xx025/carrot#369]
网址： https://chat.0.bnu120.space/

我是站长，这个网站有很多条线路，太多了不好管理，因此我做了一个索引站，希望能把用户都导向这里，谢谢。这样我也好同步对每条不同架构的线路发公告

希望能把 [chat.0.bnu120.space](https://chat.0.bnu120.space/) 改成 [index.chat.bnu120.sapce](https://index.chat.bnu120.space/)

即使线路被封，这个索引站应该也不会被封。尽量不再给你们添加麻烦了🙏

**Comment by xx025** [comment]
没问题，

但是我感觉你这个索引站目前国内网络也不能打开

**Comment by xx025** [comment]
![Screenshot_20230428_110717.jpg](https://user-images.githubusercontent.com/71559822/235045031-b43de33b-bdc5-4af0-a783-3fe6f7a148da.jpg)

**Comment by xx025** [comment]
🆗，已更新
