### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by qingtiandamowang** [xx025/carrot#371]
**网址**

```
http://1.chatai.baby/
```
**网站类型**

- [] ChatGPT站点

**网站简介、使用方式****

> 请尽量描述清楚，各行方便
> 会给据使用方式分配权重，如: 免费> （付费+体验次数）> 付费 

-  😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [x]🤑 付费使用 
- [x]🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

否

**Comment by xx025** [comment]
🆗，已添加

**Comment by qingtiandamowang** [comment]
&nbsp;
1.chatai.baby
免费使用无需任何秘钥 麻烦管理员更改


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xx025/carrot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xx025/carrot] [添加站点]  (Issue #371)





 
🆗，已添加

**Comment by qingtiandamowang** [comment]
&nbsp;
1.chatai.baby
现在需要&nbsp;✈️所以有换了个域名 害怕以后长期麻烦管理员 麻烦你把域名改成这个 chat.chatai.baby&nbsp; 这样以后就不用天天麻烦管理员了


还是免费使用无任何限制&nbsp; &nbsp;
5.1快了 打扰您了


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xx025/carrot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月28日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xx025/carrot] [添加站点]  (Issue #371)





 
🆗，已添加
