### ISSUE TITLE
[添加站点] https://ai-pig-fly.space/

### ISSUE THREAD

**Issue by qdzhaoxiaodao** [xx025/carrot#372]
**网址**

```
https://ai-pig-fly.space/
```
**网站类型**

- [x] ChatGPT 全球站点整合
- [ ] 其他

**网站简介、使用方式****

> 无需魔法，打开即用
> 会给据使用方式分配权重，如: 免费> （付费+体验次数）> 付费 

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://ai-pig-fly.space/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by huanfeng123** [comment]
小旋风chat 域名被墙原始域名 http://gpt.gpt0.icu/
新域名：https://gpt.ai8.icu/
麻烦更换

**Comment by xx025** [comment]
🆗，已添加

**Comment by 2-2-001** [comment]
应该是整理成了一个入口吧，反正能用就行，哈哈

**Comment by haowani** [comment]
挺好用的，好像打不开了😭😭
