### ISSUE TITLE
有些chatgpt镜像实际上没法使用或者处于商业目的

### ISSUE THREAD

**Issue by asmwarrior** [xx025/carrot#4]
例如这个网站：

https://askai.ws/

即便注册了，也只能使用3次的交互问答。

> 尊敬的 您好，您今日剩余可用AI问答次数为：3次

这种网站，感觉主要是赚钱的，建议加以标注

**Comment by xx025** [comment]
> 例如这个网站：
> 
> https://askai.ws/
> 
> 即便注册了，也只能使用3次的交互问答。
> 
> > 尊敬的 您好，您今日剩余可用AI问答次数为：3次
> 
> 这种网站，感觉主要是赚钱的，建议加以标注

可提交详细标注pr，我时间不太充裕

**Comment by xx025** [comment]
如：
1. www.github.com
   >github官网
