### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by Tomccc520** [xx025/carrot#400]
**网址**

```
https://tomda.xyz/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，各行方便
> 
- [ ] 🔑 免费使用但是需要登录或密码

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
