### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by Darrickzhiyi** [xx025/carrot#406]
**网址**

```
https://chat.darricks.net/
```
**网站类型**

- [x] ChatGPT站点

**网站简介、使用方式****

> 需要密码（要在“设置”里面填写密码）
> 密码：j-2004

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
