### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by cytsese** [xx025/carrot#420]
**网址**

```
https://chatgpt.cytsee.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

免费提供国内用户使用，无需注册登陆

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://chatgpt.cytsee.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
