### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by pzh-2009** [xx025/carrot#462]
网址： [N1.xjai.cc](https://day0424.ai55.cc/url/?id=bzdHN29yMjhadllJQlRuVW1TZkZIbVB3eWsvNW90bmZXbGxseDJmeEVyZz0=)

问题：GPT-4变更为付费使用，AI绘画及GPT-3.5免费

**Comment by xx025** [comment]
感谢反馈，🆗，已更新
