### ISSUE TITLE
add some new websites

### ISSUE THREAD

**Issue by niguige** [xx025/carrot#47]
https://docsgpt.arc53.com/
https://typeset.io/
https://chatexcel.com/
https://b.jimmylv.cn
https://yiyan.baidu.com/welcome
https://chat-gpt.nikong.cn/home
https://chatapi.qload.cn/
https://ask.aiservices.tech/
https://chat.moyunav.com/
https://gpt.tool00.com/
https://chat.binjie.site:7777/
http://zhimachat.com/

**Comment by xx025** [comment]
技术文档助手 https://docsgpt.arc53.com/

**Comment by xx025** [comment]
表格助手 https://chatexcel.com/

**Comment by xx025** [comment]
研究助手 https://typeset.io/

**Comment by niguige** [comment]
海豚问答 http://zhimachat.com/

**Comment by xx025** [comment]
我还在检查上面的，非常感谢分享♥

**Comment by xx025** [comment]
> 海豚问答 http://zhimachat.com/

我还在检查上面的，非常感谢分享♥

**Comment by xx025** [comment]
https://chat.moyunav.com/
已不再解析

**Comment by xx025** [comment]
https://chat.binjie.site:7777/

已有其它cf域名,https://chat.yqcloud.top/

**Comment by xx025** [comment]
> https://docsgpt.arc53.com/ https://typeset.io/ https://chatexcel.com/ https://b.jimmylv.cn https://yiyan.baidu.com/welcome https://chat-gpt.nikong.cn/home https://chatapi.qload.cn/ https://ask.aiservices.tech/ https://chat.moyunav.com/ https://gpt.tool00.com/ https://chat.binjie.site:7777/ http://zhimachat.com/

非常感谢您的分享♥，上面的网站已经检查完毕，部分站点不属于chatgpt类网站，故从新设置分类**妙站**，并收录于此
