### ISSUE TITLE
[添加站点] 2个不限量

### ISSUE THREAD

**Issue by wangjueszu** [xx025/carrot#477]
**网址**

```
服务器1：https://b1n.net/6H7OF（GPT3.5+GPT4.0）
服务器2：https://b1n.net/ypv3K  （纯GPT3.5）
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

无使用次数限制，两个网址的账户和密码均相同，网址体验上稳定。

- [] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
  公共账户：Sydney-Ai
  密码：Sydeny-Ai（与账户不一致）
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
