### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by Wtcityx** [xx025/carrot#481]
网址： https://nb.nbai.live/#/chat/1002
![image](https://user-images.githubusercontent.com/95459923/236675339-1a58ab21-fd95-4847-94cb-bf1da0439a8c.png)

问题：骗钱，假的GPT-4！！！！

**Comment by xx025** [comment]
🆗，感谢反馈

**Comment by xx025** [comment]
我没找到这个域名，请问是从哪个网址跳转过去的

**Comment by Wtcityx** [comment]
我的失误，智商是在线的是gpt-4，只不过设定了前置prompt让人误解
