### ISSUE TITLE
[添加站点] https://chatgptdddd.com

### ISSUE THREAD

**Issue by zsodur** [xx025/carrot#487]
**网址**

```
https://chatgptdddd.com
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**

```
http://chatgptdddd.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
