### ISSUE TITLE
如果您不希望您的网站出现在此列表，请在此附言

### ISSUE THREAD

**Issue by xx025** [xx025/carrot#50]
为防止恶意提交，请附上**证明您拥有其顶级域名权限**的材料

### 🙅‍ site list

- https://askai.ws/

**Comment by aTool00** [comment]
移除 gpt.tool00.com
证明：https://gpt.tool00.com/carrot.txt

**Comment by xx025** [comment]
已处理


> 移除 gpt.too**.com 证明：https://gpt.tool**.com/carrot.txt

**Comment by xx025** [comment]
已记录
> 我这个ChatGPT镜像站点也是可以的。可以添加的。 http://ai.bo-e.com/
