### ISSUE TITLE
感谢收录本站：https://chat.bo-e.com/

### ISSUE THREAD

**Issue by xx025** [xx025/carrot#514]
感谢收录本站：https://chat.bo-e.com/

_Originally posted by @cnxuzhou in https://github.com/xx025/carrot/discussions/513_

**Comment by cnxuzhou** [comment]
排名太靠后了，前20排不上吗

**Comment by xx025** [comment]
> 排名太靠后了，前20排不上吗

目前的排序算法是，会把不需要登陆的排在前面；
