### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by Wtcityx** [xx025/carrot#533]
**网址**

```
https://new-bing.club/chat
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****
免费3.5，付费GPT-4

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
