### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by chataibase** [xx025/carrot#536]
**网址**

```
https://chataibase.com
```
**网站类型**

- [x] 免费ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 网站提供各种好玩的基于ChatGPT和MidJourney的免费小工具

- [x] 😄 免费使用(未登陆每个小时10次聊天，登陆后每小时30次)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://chataibase.com/openaigym.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加

**Comment by chataibase** [comment]
您好 请求您更换域名 该域名已经被墙···· 最新域名 infiniteai.chat

**Comment by xx025** [comment]
🆗，已更新

**Comment by chataibase** [comment]
感谢

**Comment by chataibase** [comment]
您好～似乎还没合并上去··不好意思再次打扰您
