### ISSUE TITLE
[反馈] 网站内容更新

### ISSUE THREAD

**Issue by CatAnd-Dog** [xx025/carrot#538]
原网址为：
https://srgfdfsf.xiaowenzi.xyz/
此网址仍然可用。但是更新了一个永久发布页。
https://gpt.lovebaby.today/
更新内容：
删除了密码访问，无需国际网络，开箱即用。
使用了120美刀账号。没有任何速率限制，访问速度飞快。
每分钟的回复次数高达三千次。（免费5刀账户只有3次）

没有任何使用限制。可以自定义模型参数。自由度超高。
麻烦作者增加一下推荐权重，谢谢。承诺永久免费使用。

The original website is:

https://srgfdfsf.xiaowenzi.xyz/

This site is still available. But a permanent publish page has been added.

https://gpt.lovebaby.today/

What's New:

Password access removed, out of the box.

I used a $120 account. There is no speed limit and access is fast.

There are as many as 3,000 replies per minute. (Free $5 account only 3 times)

There are no restrictions on use. You can customize the model parameters. High degree of freedom.

Please kindly ask the author to increase the recommended weight, thank you. Promise to use it free forever.

**Comment by xx025** [comment]
🆗，已添加

**Comment by xx025** [comment]
🆗，已添加
