### ISSUE TITLE
[添加站点] https://ct1.xiami.monster/

### ISSUE THREAD

**Issue by johnsonwong666** [xx025/carrot#544]
**网址**

```
https://ct1.xiami.monster/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****
免费无限制 可以画画 可以对话

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加

**Comment by johnsonwong666** [comment]
> 🆗，已添加

希望能加个图标

https://ai.xiamis.xyz/static/img/ic_ai.png

**Comment by johnsonwong666** [comment]
> > 🆗，已添加
> 
> 希望能加个图标
> 
> https://ai.xiamis.xyz/static/img/ic_ai.png

顺便加个 描述可以嘛 免费3.5 免费画图
