### ISSUE TITLE
[反馈] 网站收录分享

### ISSUE THREAD

**Issue by shartoo** [xx025/carrot#552]
网址： https://www.webhub123.com/#/home/detail?p=5wjI7-3fpAW

问题：将本仓库中分享的使用ChatGPT办公的网站整理到 该网址了，用户可以像github一样一键fork到自己的收藏，管理起来更方便，每个网站可以随意修改。管理和分享网站是完全免费的。

![3312](https://github.com/xx025/carrot/assets/5716282/de1022bd-6419-434d-9255-cda554d17b75)

**Comment by xx025** [comment]
谢谢，当前已有一个 简单的web服务 同时 管理 github repo 和 发布网站
