### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by HebutMrLiu** [xx025/carrot#556]
**网址**

```
https://chat.hyyddx.eu.org/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 完全免费

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**是否需要国际网络**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
https://github.com/xx025/carrot/issues/557

指向相同的域名
