### ISSUE TITLE
[反馈] 

### ISSUE THREAD

**Issue by lucaslu1212** [xx025/carrot#586]
![image](https://github.com/xx025/carrot/assets/122723079/359cdc9a-4198-4d2b-8dea-69fa4d3500a2)

问题：如网站失效

**Comment by lucaslu1212** [comment]
> ![image](https://user-images.githubusercontent.com/122723079/241836186-359cdc9a-4198-4d2b-8dea-69fa4d3500a2.png)
> 
> 问题：网站失效

**Comment by xx025** [comment]
感谢反馈，🆗，已更新
