### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by cnxuzhou** [xx025/carrot#596]
**网址**
https://chat.bo-e.com

网站类型:   hatGPT站点

网站简介：博弈Ai-基于ChatGPT4及3.5的智能聊天机器人国产镜像

使用方式:   微信扫码登陆

是否收费： 免费使用

网站图标：https://chat.bo-e.com/icon.svg

是否需要国际网络：否

**Comment by xx025** [comment]
🆗，已添加
