### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by FlaresAI** [xx025/carrot#599]
**网址**

```
https://chat.flares.ai
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

GPT-3.5不需要登陆，免费使用，没有次数限制，登陆可用GPT-4

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://assets.flares.ai/openaigym.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
