### ISSUE TITLE
[ruandi.net] 

### ISSUE THREAD

**Issue by gtaboo** [xx025/carrot#602]
**网址**

```
https://ruandi.net/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 问想AI-让AI协助你迸发灵感

- [] 😄 免费使用(打开即可用无限制)
- [ x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
