### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by imagine996** [xx025/carrot#609]
**网址**

```
http://www.im9.cc
```
**网站类型**

- [x] ChatGPT站点
- [x] 其他

**网站简介、使用方式****

> 登录即可免费使用chatgpt以及SD绘图工具

- [x] 😄 免费使用(每月免费40,000Token)
- [x] 🔑 免费使用但是需要登录或密码

**网站图标-路径(可选)**
> https://www.im9.cc//storage/logo/1732607499.png

```
如: https://www.im9.cc//storage/logo/1732607499.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
