### ISSUE TITLE
[添加站点] https://www.ai2dog.com/bavarder

### ISSUE THREAD

**Issue by manjinxin** [xx025/carrot#613]
**网址**

```
https://www.ai2dog.com/bavarder
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用
开箱即用，登录后可体验GPT4，已接入多种场景模式（如文章润色、小红书文案生成等），已接入图像理解能力。

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
[如: http://example.com/favicon.ico](https://www.ai2dog.com/favicon.ico)
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
