### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by ticktack** [xx025/carrot#619]
**网址**
AIGC小站
```
https://chatgpt.kungfu.wang/
```
**网站类型**

- [x] ChatGPT站点
- [x] AI绘画

**网站简介、使用方式****

> 隆重推出AIGC小站（AI生成内容服务），提供ChatGPT, AI绘画、语音、翻译等功能。无需翻墙，无需注册账号。

- [x] 🔑 免费使用但是需要登录

**网站图标-路径(可选)**
> https://chatgpt.kungfu.wang/favicon.png

```
https://chatgpt.kungfu.wang/favicon.png
```

**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
🆗，已添加
