### ISSUE TITLE
cc.ai55.cc疑似被墙

### ISSUE THREAD

**Issue by dddddgz** [xx025/carrot#620]
无法访问了

**Comment by xx025** [comment]
很久之前就这样了

**Comment by dddddgz** [comment]
> 很久之前就这样了

az，今天才注意到
之前可以访问的时候看到 chat.binjie.site 的时候就收藏了，然后被墙了，后来 cc.ai55.cc 也被墙了
就不知道该怎么用 ChatGPT 了
(很想用表情可是github里没有）
