### ISSUE TITLE
[添加站点]   [⭐⭐⭐] https://firstai.opao.xyz/ 国内永久免费的Chatgpt 镜像，具有3.5和4.0，均可使用

### ISSUE THREAD

**Issue by cat-dog-fish** [xx025/carrot#621]
https://firstai.opao.xyz/
无需登录即可直接使用免费的国际镜像。
此外还有联网版本的gpt和学术专用版本的gpt可以使用。详情访问网址即可。

**网址**

```
https://firstai.opao.xyz/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
