### ISSUE TITLE
[添加站点] https://ndwgsahpoamw.cloud.sealos.io

### ISSUE THREAD

**Issue by kouzhangbin** [xx025/carrot#623]
**网址**

```
http://example.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种
https://ndwgsahpoamw.cloud.sealos.io/icon/logo2.png
```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/2f4eaa2a-09ac-4626-b942-e9e0e41c26d6)
