### ISSUE TITLE
http://chatgpt.qqslyx.com/

### ISSUE THREAD

**Issue by 120018425** [xx025/carrot#644]
**网址**

```
http://chatgpt.qqslyx.com/
```
**网站类型**

- [x] 免费ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

免费chatgpt3(不定时开chatgpt4,看作者钱包情况 )，免费算命，测八字，诸多ai工具等，后续上架免费ai画图，ai换脸以及换(tuo)衣

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形那种

```
http://chatgpt.qqslyx.com/favicon.ico
```
**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
🆗，已添加
