### ISSUE TITLE
[添加站点] talks-ai

### ISSUE THREAD

**Issue by danicaStarR** [xx025/carrot#645]
**网址**

```
https://www.talks-ai.com/
```
**网站类型**

- [x] ChatGPT站点
- [x] 服务型AI

**网站简介：只需上传文档或添加网站的链接，即可训练ChatGPT聊天机器人。支持直接使用或嵌入网站，充当私人助理或客服机器人。**

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**

```
如: https://www.talks-ai.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 是

**Comment by xx025** [comment]
🆗，已添加
