### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by WHRCT22** [xx025/carrot#646]
**网址**

```
https://chatgpt.cloudwl.com
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 进入设置，接口地址填入https://ai.fakeopen.com
apikey填入
pk-this-is-a-real-free-pool-token-for-everyone

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/e613f07a-54d2-4589-ac3e-1797248ec981)
