### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by gaojunming** [xx025/carrot#651]
**网址**

```
https://home.chatplus.buzz/web.html
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 需要在设置中设置访问令牌，访问https://home.chatplus.buzz 获取令牌

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://home.chatplus.buzz/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
