### ISSUE TITLE
[添加站点]   免费直连镜像 3.5+4.0 https://aassdd.opao.xyz

### ISSUE THREAD

**Issue by CatAnd-Dog** [xx025/carrot#653]
多个版本均无限制免费使用。多种模型可以使用。还有联网功能，newbing均为免费

https://aassdd.opao.xyz/

使用了120美刀账号。没有任何速率限制，访问速度飞快。
每分钟的回复次数高达三千次。（免费5刀账户只有3次）

没有任何使用限制。可以自定义模型参数。自由度超高。
麻烦作者增加一下推荐权重，谢谢。承诺永久免费使用。

https://aassdd.opao.xyz/

What's New:

Password access removed, out of the box.

I used a $120 account. There is no speed limit and access is fast.

There are as many as 3,000 replies per minute. (Free $5 account only 3 times)

There are no restrictions on use. You can customize the model parameters. High degree of freedom.

Please kindly ask the author to increase the recommended weight, thank you. Promise to use it free forever.

**Comment by xx025** [comment]
🆗，已更新
