### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by onlyGuo** [xx025/carrot#664]
**网址**

```
https://free.icoding.ink/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 1. 开箱即用，无需任何额外准备工作。
> 2. 含APP(IOS直接在商店搜索"智友AI", 安卓需要在下载页手动下载安装)

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://chat.icoding.ink/assets/images/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
