### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by CrushiY** [xx025/carrot#667]
**网址**

```
https://gptplus.io/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> GPTPLUS：国内ChatGPT工具，用于写作、翻译以及更多功能。由GPT-4和GPT-3.5提供技术支持的GPTPLUS，为您的写作、翻译、代码分析、问答需求提供最准确有效的AI反馈。您可以随时在侧边栏上与ChatGPT人工智能助手聊天和互动。

- [] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://zbase-global.zingfront.com/saasbox/product/icon/3053f8b75acbb15e2c6c9668414d3374.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
