### ISSUE TITLE
站点gpt对话失效，并需要注册登陆，付费充值获得使用次数

### ISSUE THREAD

**Issue by mumujinx** [xx025/carrot#67]
http://chatai.fyi/

**Comment by xx025** [comment]
> http://chatai.fyi/

尝试了几轮对话，感觉是没问题，暂时先不做修改

[图片](https://user-images.githubusercontent.com/71559822/226297401-9d62d0a3-11c1-4330-a0b4-d19f2c42178c.gif)
![动画2](https://user-images.githubusercontent.com/71559822/226297401-9d62d0a3-11c1-4330-a0b4-d19f2c42178c.gif)
