### ISSUE TITLE
gpt公益站

### ISSUE THREAD

**Issue by a2737** [xx025/carrot#672]
**[gpt公益站](https://nav.chatkey.top/)**

```
https://nav.chatkey.top/
```
**免费无广，无需登陆打开即可使用**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用

- [x] 😄 免费使用(打开即可用无限制)

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
