### ISSUE TITLE
[反馈] 失效链接更新

### ISSUE THREAD

**Issue by CNSeniorious000** [xx025/carrot#679]
网址： https://free-chat.asia

问题：index.chat.bnu120.space 更新域名

因为这个域名的备案被管局收回了，域名解析也被强制下线了，我甚至都没法配置重定向😭希望能修改一下，改成 free-chat.asia 这个域名。

我们的features是：沉浸式UI、自愿捐赠、可一键私有化部署

thanks!

**Comment by xx025** [comment]
🆗，已更新
