### ISSUE TITLE
站点使用受限，需要注册登陆绑定设备，并付费充值获得使用次数

### ISSUE THREAD

**Issue by mumujinx** [xx025/carrot#68]
https://trychatgp.com/

**Comment by xx025** [comment]
> https://trychatgp.com/

我测试了几轮对话，感觉正常使用；

暂时先搁置

**Comment by xx025** [comment]
![动画](https://user-images.githubusercontent.com/71559822/226295814-196a51e6-1599-40d8-bf35-58cf76202647.gif)
