### ISSUE TITLE
[添加站点]

### ISSUE THREAD

**Issue by thundernet8** [xx025/carrot#688]
**网址**

```
https://aixforce.app/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 以应用模式打造常用的ChatGPT模板，支持生成模式、对话模式以及基于私有文档的QA，另外提供MidJoury以及Dalle AI智能绘画。网站提供匿名试用，登录每日赠送额度

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://aixforce.app/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
