### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by tomridder** [xx025/carrot#692]
**网址**

```
http://example.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用

- [] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```

https://www.tomchat.work

· 支持gpt4 -3.5
· 支持 midjourny绘画 
·支持16k长篇写作
·无使用月限额

```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/16c73025-fcea-4d1f-81d5-65c569d2a3f5)
不可用
