### ISSUE TITLE
[添加站点] https://chatz.free2gpt.xyz

### ISSUE THREAD

**Issue by usechatgptlive** [xx025/carrot#697]
网址
https://chatz.free2gpt.xyz

唠嗑唠嗑
目前第9个也是我的站点: chat.free2gpt.xyz 但已被墙, 希望可以替换一下域名😁
这个被墙也是没啥办法, 为了能存活久一点, 我做个尝试:

1. 使用 chatZ.free2gpt.xyz 重定向到 chatH.free2gpt.xyz
2. 收录投稿chatZ
3. 因为chatZ只做重定向, 被墙的概率小些, 当chatH被墙后, 只需修改chatZ重新重定向到新的域名chatI即可, 导航站链接依然可用

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

完全免费 无需魔法 无需登录 不限次数 界面简洁 无弹窗广告

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已更新
