### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by leadscloud** [xx025/carrot#705]
**网址**

```
https://chat.tinycms.xyz:3002/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 免费GPT3.5使用，GPT-4使用的是webapp模式，3小时50次
> 支持New bing, Google Bard,百度文心一言

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 无

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
