### ISSUE TITLE
[添加站点] 柏拉图次元AI 无限制3.5，可免费体验 4.0，MJ

### ISSUE THREAD

**Issue by xyfacai** [xx025/carrot#722]
**网址**

```
http://bltcy.com/
```
**网站类型**

- [x] ChatGPT站点
- [x] 其他

**网站简介、使用方式****

GPT3.5 完全免费，可免费体验GPT4.0，MJ绘画，无需魔法，无广告

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
