### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by luzhenhua1** [xx025/carrot#728]
**网址**

```
https://beta.bushiai.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 目前可用模型GPT3.5 turbo 16k，国内的大模型有百度文心，开发者说后期会接入阿里千问和MJ绘画

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://beta.bushiai.com/api/file/10f42dc6-006a-45d1-8cb5-831ae9ce250b
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
