### ISSUE TITLE
[Poe.Monster](https://poe.monster/)

### ISSUE THREAD

**Issue by terobox** [xx025/carrot#734]
**网址**

```
https://poe.monster/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 专业的ChatGPT对话系统，首次登录赠送 1000 对话积分

- [] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://poe.monster/favicon.svg
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by brucewangde** [comment]
网址：
[www.znzs.me](url)
网站类型：
 ChatGPT站点
🔑 3.5免费使用但是需要登录或密码，注册送99999999 tokens
国内可以访问
