### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by lau1944** [xx025/carrot#736]
**网址**

```
https://tubogpt.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> GPT4 次数付费 可生成图片

- [x] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [x] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

<img src="https://play-lh.googleusercontent.com/Qo0vfZBwp-QzcRaUvuYDXmZQLznswwBGdBKJDMpNvFVhDliKrt9sKnzgnTaFfrBLDRw=w480-h960-rw"  width="100" height="100"/>
```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
🆗，已添加
