### ISSUE TITLE
ChatGPT API 水龙头

### ISSUE THREAD

**Issue by terobox** [xx025/carrot#737]
**网址**

```
https://faucet.openkey.cloud/
```
**网站类型**

- [] ChatGPT站点
- [x] 其他

**网站简介、使用方式****

> AI 圈的水龙头网站, 每24小时可领取一个令牌用于开发测试 AI 产品. 默认情况下, 令牌有 $1.00 的使用限制, 有效期为1个月. 这是完全免费的, 请勿滥用.

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://terobox.oss-cn-hongkong.aliyuncs.com/openkey/faucet-logo.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**推荐理由**
twitter点赞破百
https://twitter.com/bluebird0605/status/1706109742123253956
ahhhhf收录
https://www.ahhhhfs.com/47681/

**Comment by xx025** [comment]
🆗，已添加
