### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by brucewangde** [xx025/carrot#741]
**网址**

```
http://www.znzs.me/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 用户可以免费使用3.5模型，每天限制10万tokens，全速版和4.0包月收费（无使用限制）

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [x] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/a7b2e83b-18b3-497e-9289-275ce8dfde6b)

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/75ba4f77-4ed6-45f0-bc9e-58bcabd0836b)

**Comment by brucewangde** [comment]
http://znzs.me/chat

**Comment by xx025** [comment]
已更新
