### ISSUE TITLE
[添加站点] 云行 AI：http://chatai.yxboot.com/

### ISSUE THREAD

**Issue by boyazuo** [xx025/carrot#747]
**网址**

```
http://chatai.yxboot.com/
```

**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式**
云行 AI，直接访问，稳定、快速。
注册、分享赠送免费次数，付费不限次使用。

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [x] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**

```
http://chatai.yxboot.com/common/logo-home.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
https://github.com/xx025/carrot/issues/724
