### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by Tan6543214** [xx025/carrot#752]
**网址**

```
https://chat.chuanwen.top/
```
**网站类型**

- [x] ChatGPT站点+集成chatgpt，文心一言，星火大模型，清华智库大模型

**网站简介、使用方式****
开箱即用，集成chatgpt，文心一言，星火大模型，清华智库大模型

> 请尽量描述清楚，方便其他人使用

- [ ] 🤑 付费使用 

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://www.chuanwen.top/images/dog.jpg
```

**是否需要国际网络(可选)**

- [x] 否

希望大佬们能把我排前面一点，服务器稳定，速度快。感谢！

**Comment by Somnus1437** [comment]
https://www.ealxc.cn
