### ISSUE TITLE
[添加站点] aivesa.cn

### ISSUE THREAD

**Issue by ClarenceDan** [xx025/carrot#754]
**网址**

```
aivesa.cn
```
**网站类型**

- [x] ChatGPT站点，长期提供免费的GPT3.5，GPT-4.0和讯飞星火大模型
- [ ] 其他

**网站简介、使用方式****

> 网站已稳定运行半年，全球直连无需国际网络，目前支持免费不限量的GPT-3.5，GPT-4.0和讯飞星火大模型，欢迎使用，欢迎体验。

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://aivesa.cn/images/icon.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
