### ISSUE TITLE
[添加站点] xiamis.xyz

### ISSUE THREAD

**Issue by johnsonwong666** [xx025/carrot#755]
**网址**

```
https://fby.xiamis.xyz/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 请尽量描述清楚，方便其他人使用

希望可以放到比较前面一点，备案域名，阿里云国内服务器，大带宽，站点访问快速、稳定可靠

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种
https://ylb.xiamis.xyz/console/upload/2023-11-10-618.png
```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
