### ISSUE TITLE
[添加站点] 福牛AI

### ISSUE THREAD

**Issue by funiu6** [xx025/carrot#760]
**网址**

```
https://ai.funiu6.com/
```
**网站类型**

- [√] ChatGPT公益站点

**网站简介、使用方式****

- [√] 😄 免费使用(打开即可用无限制)

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://ai.funiu6.com/favicon.png
```

**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
由于长时间每一回复，暂时先关闭了，如有需要可以再次打开
