### ISSUE TITLE
[添加站点] http://gpt4.aiseo.lat/triglav/index

### ISSUE THREAD

**Issue by webpon** [xx025/carrot#762]
**网址**

```
http://gpt4.aiseo.lat/triglav/index
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****
免费无限制使用gpt4，无需登录

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
网站被定向到 https://www.gnomic.cn/ 已添加  https://www.gnomic.cn/
