### ISSUE TITLE
[反馈] airoom为什么权重下降？

### ISSUE THREAD

**Issue by henryhu712** [xx025/carrot#767]
网址： https://airoom.chat/

问题：该网站仍然保持不用登录、不用翻墙、免费，为什么权重降低了？是不是某个因素误解了？Playground是没有变化的，只是gpt4需要登录。

**Comment by xx025** [comment]
因为会进行打乱排序

![image](https://github.com/xx025/carrot/assets/71559822/7344d0b9-98d0-4965-9530-74ab759ac82d)
