### ISSUE TITLE
[添加站点] 

### ISSUE THREAD

**Issue by kx2398** [xx025/carrot#779]
**网址**

```
https://gpt4.intercat.cn/
```
**网站类型**

-  ChatGPT站点

**网站简介、使用方式****

> GPT4免费站点，打开链接自动跳转到最新页面，内页链接约2-3天会更新一次，需从https://gpt4.intercat.cn 进入。
> 免费使用，不需要登录

- [x] 😄 免费使用(打开即可用无限制)

**是否需要国际网络(可选)**

- [x] 否

**Comment by xx025** [comment]
域名已在数据库，已更新
