### ISSUE TITLE
这个打不开

### ISSUE THREAD

**Issue by shiftgirl** [xx025/carrot#78]
https://[www.aitoolgpt.com](https://www.aitoolgpt.com/)/

**Comment by xx025** [comment]
![image](https://user-images.githubusercontent.com/71559822/226564919-54978de1-f69a-4e81-ad74-48b4f5942bcd.png)

已测试，可以访问，可以尝试清除浏览器记录 cookies 再访问

**Comment by shiftgirl** [comment]
这是来自QQ邮箱的假期自动回复邮件。

您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shiftgirl** [comment]
试过了好几个设备和ip，让别人也试了访问不了

**Comment by xx025** [comment]
这个站应该是需要代理，我没有代理我也打不开
