### ISSUE TITLE
比心网

### ISSUE THREAD

**Issue by qformat** [xx025/carrot#780]
**网址**

```
https://1.bixin123.com/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

> 直接对接官方API，架设极速cnd技术，免翻墙速度快，全球可用，不只是ChatGPT免费，其中还包括AI绘图，ChatGPT3.5和ChatGPT4.0都有，内置各种模型应用，包括但不限于：家庭医生，编程助手，励志演讲，招聘人员，私人教练，产品经理，全语种翻译，数学老师，职业顾问，IT架构师，网络安全专家，医生，诗人，小红书Emoji风格文案，MJ提示词生成，写作助理，求职信等众多的应用，玩的溜的还可以私人定制模块，定制内容不限，没有任何限定，因此想怎么玩就怎么玩，关键是免费，免费，免费！

- [x] 😄 免费使用ChatGPT4.0
- [x] 🔑 免费使用GPT3.5

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
