### ISSUE TITLE
[添加站点] https://chat.aiptl.com  重点是免费支持GPT-4

### ISSUE THREAD

**Issue by Somnus1437** [xx025/carrot#782]
**网址**
https://chat.aiptl.com
```
https://chat.aiptl.com
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

免费支持GPT-4
> 请尽量描述清楚，方便其他人使用
无需注册
无需国际网络
打开即用
支持所有的ChatGPT模型
免费可以无限使用GPT-4

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加

**Comment by huangxu510** [comment]
这个不免费啊，要输入密码或者apiKey

**Comment by xx025** [comment]
> 这个不免费啊，要输入密码或者apiKey

已更新，感谢反馈
