### ISSUE TITLE
易米AI

### ISSUE THREAD

**Issue by Kirogodme** [xx025/carrot#785]
**网址**

```
http://ymi.ai/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 全球热门模型集合体

**网站简介、使用方式****

> 网站集合了全世界最热门的模型供大家学习使用，操作界面非常简单易上手

- [x] 
- [ ] 
- [ ] 🤑 付费使用 
- [ ] 

**网站图标-路径(可选)**
> 正方形 那种

```
如: http://example.com/favicon.ico
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加

**Comment by Kirogodme** [comment]
你好，需要麻烦你们一下，之前提交的链接有误，能否帮助修改下链接为： https://ymi.ai/?channel=J03


姜涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xx025/carrot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 上午9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xx025/carrot] 易米AI (Issue #785)





 
已添加

**Comment by xx025** [comment]
已更新

**Comment by Kirogodme** [comment]
非常感谢

姜涛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xx025/carrot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 上午9:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xx025/carrot] 易米AI (Issue #785)





 
已更新
