### ISSUE TITLE
添加一个 支持知识库支持GPT4，GPT4图文对话，支持售卖知识库。

### ISSUE THREAD

**Issue by 239573049** [xx025/carrot#788]
**网址**

```
https://open666.cn
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****

>TokenAI 支持应用市场售卖购买，支持知识库售卖购买，和自定义私有化知识库，支持GPT4。

- [ ] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://chat.open666.cn/icons/icon-192x192.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
