### ISSUE TITLE
试过了好几个设备和ip，让别人也试了访问不了

### ISSUE THREAD

**Issue by shiftgirl** [xx025/carrot#79]
试过了好几个设备和ip，让别人也试了访问不了

_Originally posted by @shiftgirl in https://github.com/xx025/carrot/issues/78#issuecomment-1477561564_

**Comment by xx025** [comment]
我又测试了一下，这个站需要代理服务才能打开

感谢再次反馈❤，可以试试其他站点，如有问题欢迎告诉我

**Comment by shiftgirl** [comment]
刚刚突然好几个站都打不开了

**Comment by xx025** [comment]
> 刚刚突然好几个站都打不开了

如果你本机使用代理，也可能是代理的原因，如果还有问题欢迎告诉我
