### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by qwIvan** [xx025/carrot#794]
**网址**

```
https://share.aiwenda.chat
```
**网站类型**

- [x] ChatGPT镜像
- [x] 可以使用ChatGPT plus的所有功能
- [x] GPT-4
- [x] 联网搜索
- [x] 数据分析
- [x] DALL E 画图
- [x] gpt-4-vision 识图
- [x] 内置GPTs商店
- [x] 不限次数
- [x] 无需登录

**网站简介、使用方式**

> - GPT-4
> - 联网搜索
> - 数据分析
> - DALL E 画图
> - gpt-4-vision 识图
> - GPTs商店

- [x] 😄 免费使用(打开即可用无限制)
- [ ] 🔑 免费使用但是需要登录或密码
- [ ] 🤑 付费使用 
- [ ] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
https://share.aiwenda.chat/_next/static/media/apple-touch-icon.59f2e898.png
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by qwIvan** [comment]
对不起，之前放错了链接。现在修正了

**Comment by xx025** [comment]
已添加
