### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by SH-alaways** [xx025/carrot#796]
!
>必须付费才能使用的就不要提交了

**网址**

```
https://newchat.hklan.top/
```
**网站类型**

- [x] ChatGPT站点
- [ ] 其他

**网站简介、使用方式****
登录后每天赠送3.5+4.0+MJ绘画次数，轻度使用者可永久白嫖
> 请尽量描述清楚，方便其他人使用

- [ ] 😄 免费使用(打开即可用无限制)
- [x] 🔑 免费使用但是需要登录或密码
- [x] 🤑 付费使用 
- [x] 🎁 付费使用，体验次数

**网站图标-路径(可选)**
> 正方形 那种

```
如: https://bu.dusays.com/2023/07/12/64aea01f86060.webp
```

**是否需要国际网络(可选)**

- [x] 否
- [ ] 是

**Comment by xx025** [comment]
已添加
