### ISSUE TITLE
站点被墙

### ISSUE THREAD

**Issue by binjie09** [xx025/carrot#80]
我是作者，chat.yqcloud.top被墙了，建议替换成没被墙的地址 https://dev.yqcloud.top  https://chat1.binjie.site:7777/
<img width="637" alt="image" src="https://user-images.githubusercontent.com/18377378/226588313-a6d4c49d-0d50-4fc2-8f88-191d97def14d.png">

**Comment by binjie09** [comment]
这是两个完全不同的服务器，https://chat1.binjie.site:7777 是国内服务器  其中chat1可以换成chat1-9，yqcloud.top 是cloudflare容易被墙

**Comment by xx025** [comment]
已更新，` https://dev.yqcloud.top/`
