### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by zwc4228986** [xx025/carrot#800]
请提供以下内容：

- 标题: 暗虫AI
- 链接：https://chat.anchongai.com
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：gpt3.5无限用

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
