### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by lnformat** [xx025/carrot#801]
- 标题：PhantoNav AI
- 链接：https://chat.zonas.wang
- 图标：https://chat.zonas.wang/icons/gpt-32x32.ico
- 描述：免费GPT4，不用注册，不用登录

**Comment by xx025** [comment]
已更新
![image](https://github.com/xx025/carrot/assets/71559822/4aaf2e39-514c-490b-8b79-ca305620242f)
