### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by qwIvan** [xx025/carrot#802]
请提供以下内容：

- 标题: AI问答宝
- 链接：https://ai.wendabao.net
- 图标：https://ai.wendabao.net/bot.png
- 描述：免费GPT-4，支持联网搜索、画图，无需登录

**Comment by Nanxunn** [comment]
标题: Chkzh-Aink
链接：https://nx.chkzh.com/
图标：https://pic.imgdb.cn/item/65b35a75871b83018ad12ede/favicon.ico
描述：免费无限制GPT-3.5turbo，无需登录，打开即用

**Comment by xx025** [comment]
> * 免费GPT-4，支持联网搜索、画图，无需登录

已添加

![image](https://github.com/xx025/carrot/assets/71559822/7a5a77cd-733e-492b-b928-48b3c8d777a4)

**Comment by xx025** [comment]
> https://pic.imgdb.cn/item/65b35a75871b83018ad12ede/favicon.ico

已添加

![image](https://github.com/xx025/carrot/assets/71559822/fd41395f-9069-401d-bc24-a96f1d11b5e3)
