### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by GrimPixel** [xx025/carrot#807]
请提供以下内容：

- 标题: TalkAI
- 链接：https://talkai.info/
- 图标：https://talkai.info/files/bot.svg
- 描述：

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/34fd521f-50b1-4083-a22e-6b3572bccaf5)

**Comment by GrimPixel** [comment]
看來要加個✈️試試

**Comment by xx025** [comment]
我查看一直是下面这种情况，暂时先关掉issue了



![image](https://github.com/xx025/carrot/assets/71559822/d82be531-c685-481a-a391-7a2106544a35)
