### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by h1xy** [xx025/carrot#808]
请提供以下内容：

- 标题:   free.netfly.top
- 链接：https://free.netfly.top
- 图标：
- 描述：免注册免翻墙，gpt-4免费使用。如返回大量乱码就刷新页面

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已更新
