### ISSUE TITLE
https://chat.geekr.dev 地址变更

### ISSUE THREAD

**Issue by geekr-dev** [xx025/carrot#81]
感谢收纳 我的 GeekChat 原网址 https://chat.geekr.dev 被墙了，新网址是 https://chat2.geekr.dev，麻烦帮忙变更下，谢谢

**Comment by xx025** [comment]
十分感谢“Red Packet”


> 感谢收纳 我的 GeekChat 原网址 https://chat.geekr.dev 被墙了，新网址是 [https://chat2.geekr.dev，麻烦帮忙变更下，谢谢](https://chat2.geekr.dev%EF%BC%8C%E9%BA%BB%E7%83%A6%E5%B8%AE%E5%BF%99%E5%8F%98%E6%9B%B4%E4%B8%8B%EF%BC%8C%E8%B0%A2%E8%B0%A2)

已更新
