### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by yixuanoba** [xx025/carrot#819]
请提供以下内容：

- 标题: 创想AI
- 链接：https://ideaiai.com/
- 图标：https://ideaiai.com/favicon.ico
- 描述：免登录、免费GPT，支持GPT4，支持Midjourney绘图

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
