### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by CatAIStudio** [xx025/carrot#820]
请提供以下内容：

- 标题: 免费 Midjourney 绘画
- 链接：https://mj1.freemj.xyz/
- 图标：https://mj1.freemj.xyz/favicon.ico
- 描述：免费 Midjourney 绘画是一个提供免费 Midjourney 的 AI 绘画工具。旨在帮助 AI 绘画新人小白能够零成本快速上手 AI 绘画，赶上时代浪潮。

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
