### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by zsinba** [xx025/carrot#821]
请提供以下内容：

- 标题: LLM+RAG，支持Showdoc批量导入
- 链接：https://aid.daxue.cloud/
- 图标：https://aid.daxue.cloud/favicon.ico
- 描述：Empower Your Business with LLM & RAG。快速搭建企业知识机器人，实现数据获取与深度挖掘的加速

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
