### ISSUE TITLE
添加站点-创聚

### ISSUE THREAD

**Issue by edmondsket** [xx025/carrot#828]
请提供以下内容：

- 标题: 创聚AI
- 链接：https://icuang.top
- 图标：https://ichuang-1253296155.cos.accelerate.myqcloud.com/ai/icons8-bot-94.png
- 描述：多个大模型聚合网站，免费使用ChatGPT-3.5、4、Claude3，支持✅文档处理✅GPTs✅网络搜索✅生成图片

**Comment by zsinba** [comment]
This site can’t be reachedCheck if there is a typo in icuang.top.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by xx025** [comment]
这个网站似乎不能被打开

![image](https://github.com/xx025/carrot/assets/71559822/b79dfe23-cbaa-465e-a163-aa791761b8d3)
