### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by lupishan** [xx025/carrot#830]
请提供以下内容：

- 标题：ChatGPT原生态
- 链接：https://www.chat2chatgpt.com?from=ai555
- 图标：https://www.chat2chatgpt.com/favicon.ico
- 描述：原生态、流式响应、免登录、随时无限使用、免梯子

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/8fc7b8c0-8523-4a49-825e-864d5a33b2ab)

**Comment by lupishan** [comment]
应该是首次进入时的网络加载慢问题，麻烦再试试

标题：ChatGPT原生态
链接：[https://www.chat2chatgpt.com?from=ai555](https://www.chat2chatgpt.com/?from=ai555)
图标：https://www.chat2chatgpt.com/favicon.ico
描述：原生态、流式响应、免登录、随时无限使用、免梯子

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/790e3914-8946-473a-b0ee-8a91f68b7d63)
