### ISSUE TITLE
一设导航

### ISSUE THREAD

**Issue by qiaopeng77** [xx025/carrot#831]
请提供以下内容：

- 标题: 一设导航
- 链接：https://designtt.cc/
- 图标：https://img2.imgtp.com/2024/03/16/UIDd12w9.png
- 描述：设计风向标就看一设导航！

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/0d7a7884-129d-41db-bafa-706f054fd004)
