### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by edcloud** [xx025/carrot#835]
- 标题: 知豆Ai - AIGC聚合写作绘画
- 链接：https://www.zhidouai.com
- 图标：https://zhidou-1257550812.cos.ap-guangzhou.myqcloud.com/uploads/images/20240318/20240318141900dfdc70196.png
- 描述：免费无限制GPT3.5全模型，国内AIGC聚合网站，速度飞快，4.0、Gemini每天登录就送，真良心的平台。

**Comment by xx025** [comment]
已添加
