### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by luxlzz6** [xx025/carrot#836]
请提供以下内容：

- 标题: Ai365
- 链接：https://chat.ai365vip.com/
- 图标：https://github.com/xx025/carrot/assets/53847251/1a705b41-6862-448e-b452-c00e87d355ce
- 描述：无限制的GPT-3.5、谷歌gemini，免登录免魔法

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/21d98d81-8186-411c-b03d-f179ba08aed6)



！！！ 网站不能正常打开

**Comment by luxlzz6** [comment]
额 我这边正常的 不晓得什么原因了

**Comment by xx025** [comment]
已添加
