### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by sweetash** [xx025/carrot#839]
请提供以下内容：

- 标题: YesIamAI-是的我是AI
- 链接：yesiamai.com
- 图标：https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/120px-ChatGPT_logo.svg.png
- 描述：完全同步官网的镜像站、无限制的GPT-3.5、免登录免魔法、新注册可直接体验完整Plus功能

**Comment by sweetash** [comment]
还有貌似有邀请码可以额外获得体验时间
贴一个我自己的邀请码：QDNmS

**Comment by xx025** [comment]
![image](https://github.com/xx025/carrot/assets/71559822/af5c4835-b65a-4786-a908-1edd6a9b88f7)

**Comment by xx025** [comment]
已添加
