### ISSUE TITLE
如果您不希望您的网站出现在此仓库列表，请在此附言

### ISSUE THREAD

**Issue by xx025** [xx025/carrot#84]
为防止恶意提交，请简单附上**证明您拥有其域名权限**的材料

### site list(base64)

- YXNrYWl3LmNvbQ==
- aHR0cHM6Ly9hc2suYWlzZXJ2aWNlcy50ZWNoL2Fzaw==
-  Z3B0LnRvb2wwMC5jb20=

**Comment by jkm199** [comment]
bot.d8.pw 这个网站请下架，官方目前在通过你这个列表批量屏蔽域名

**Comment by xx025** [comment]
已移除

> bot.d8.pw 这个网站请下架，官方目前在通过你这个列表批量屏蔽域名

**Comment by beautiful-boyyy** [comment]
www.askeme.mom，没余额了

**Comment by xx025** [comment]
ok

> [www.askeme.mom](http://www.askeme.mom) 没余额了，麻烦下架一下

**Comment by Ivanlinb** [comment]
www.aiai.zone已经无法访问

**Comment by ZYB14** [comment]
太狠了，才2天api额度就被用超了，被迫下架。。

**Comment by huanfeng123** [comment]
小旋风chat 域名被墙原始域名 http://gpt.gpt0.icu/

**Comment by huanfeng123** [comment]
小旋风chat 域名被墙原始域名 http://gpt.gpt0.icu/
新域名：https://gpt.ai8.icu/

**Comment by liusishan** [comment]
xeasy.me 的所有二级域名麻烦下架一下，一被收录都会被墙

**Comment by xx025** [comment]
> xeasy.me 的所有二级域名麻烦下架一下，一被收录都会被墙，谢谢！！

🆗

**Comment by jiangzhongbo** [comment]
aigc.it did.fm dapp.cat 的所有二级域名麻烦下架一下，您这边一收录，过两天就会被q

**Comment by xx025** [comment]
> aigc.it did.fm dapp.cat 的所有二级域名麻烦下架一下，您这边一收录，过两天就会被q

🆗，已更新

**Comment by shartoo** [comment]
我也做了一个分享类似网站的网站，但是看到这些评论，有点吓人啊。为什么要这么不遗余力地封这些有用的网站

**Comment by xx025** [comment]
原则上没在国内取得经营牌照的，都有可能被阻断访问

> 我也做了一个分享类似网站的网站，但是看到这些评论，有点吓人啊。为什么要这么不遗余力地封这些有用的网站

**Comment by shartoo** [comment]
> 原则上没在国内取得经营牌照的，都有可能被阻断访问
> 
> > 我也做了一个分享类似网站的网站，但是看到这些评论，有点吓人啊。为什么要这么不遗余力地封这些有用的网站

那还能理解，如果是是针对ChatGPT有点过分。
