### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by leadscloud** [xx025/carrot#842]
请提供以下内容：

- 标题: 智能AI助手
- 链接：https://chat.tinycms.xyz:3002/
- 图标：https://chat.tinycms.xyz:3002/favicon-32x32.png
- 描述：免费的gpt3.5，免登录，可以免费使用newbing、百度文心一言、Gemini pro

之前我记得我的网站在https://cc.ai55.cc/上面，不知道什么原因取消了，我这个站稳定运行一年多了，免费的一直可以使用。

**Comment by xx025** [comment]
取消可能是，自动检查网站可用性误判

已更新
