### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by chara006688** [xx025/carrot#843]
请提供以下内容：

- 标题: Openai Chat Web
- 链接：https://ai.dfcsf.asia
- 图标：https://pic.zetatechs.com/i/2024/04/16/661e74291f84c.png
- 描述：无需梯子，注册送5点数，可访问全部模型,3.5每天限制次数免费访问,支持GPT4,GPT-4 Vision,GPTS,Claude,Dall-e,Gemini,Stable Diffusion 和 Midjourney等模型,支持文件上传，分享对话，支持使用中转api调用等

**Comment by xx025** [comment]
已添加
