### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by lin-1259** [xx025/carrot#844]
- 标题: 云衍AI
- 链接：https://chat.nuu.su
- 图标：https://tu.nuu.su/images/2024/03/28/1dd2932aa8e2f1b41cb8ea3772aa37e5.png
- 描述：3.5模型永久免费。对接官网全部GPTS应用，无需自己再写提示词，一站式AI应用，AI对话，AI绘画，AI音乐，AI视频，一套全搞定！！

**Comment by xx025** [comment]
已添加
