### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by tangfeiepng** [xx025/carrot#849]
请提供以下内容：

- 标题: share ai
- 链接：https://chat.mynanian.top/
- 图标：
- 描述：一个免费使用gpt4的地方没有套路不收一分钱

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
