### ISSUE TITLE
https://ai.cyvip.vip/

### ISSUE THREAD

**Issue by cyvipai** [xx025/carrot#850]
请提供以下内容：

- 标题: 财源AI
- 链接：https://ai.cyvip.vip/
- 图标：https://www.cyvip.vip/wp-content/uploads/2024/05/20240512182701611-chun8902_I_need_you_to_help_me_create_a_website_logo_now_the_we_f7e44fb7-8a12-40d4-89cb-023129d9ae0c.png
- 描述：免登录、免费GPT，支持GPT4，支持Midjourney绘图

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
