### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by ai-detected** [xx025/carrot#851]
请提供以下内容：

- 标题: DetectorTools.ai
- 链接：https://detectortools.ai/
- 图标：https://detectortools.ai/wp-content/uploads/2024/04/cropped-detectortools.ai-favicon21-1.png
- 描述：用于文本、深度伪造和代码的 AI 检测器工具

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
