### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by boyislfl** [xx025/carrot#856]
请提供以下内容：

- 标题: roboot
- 链接：https://robot.liujiarong.me
- 图标：https://upimage.liujiarong.me/app/thumb.php?img=/i/2023/12/31/12kpwbs.png
- 描述：免费的Chatgpt、Google AI 、Moonshot AI、Together.ai、OpenRouter、Groq等国外模型镜像。扩展插件支持MJ/SD AI生成图片。

**Comment by xx025** [comment]
已添加
