### ISSUE TITLE
添加站点,无限制免费使用 https://www.atalk-ai.com/talk

### ISSUE THREAD

**Issue by liyanan666** [xx025/carrot#857]
请提供以下内容：

- 标题: 海鲸AI
- 链接：https://www.atalk-ai.com/talk
- 图标：https://www.atalk-ai.com/favicon.ico
- 描述：多模型聚合平台，支持GPT3.5、GPT4.0，谷歌Gemini，通义千问等模型

**Comment by xx025** [comment]
已添加
