### ISSUE TITLE
更新站点信息

### ISSUE THREAD

**Issue by ziyanwould** [xx025/carrot#860]
请提供以下内容：

标题: chatnio
链接：https://chatnio.liujiarong.top
图标：https://registry.npmmirror.com/@lobehub/assets-logo/1.2.0/files/assets/logo-3d.webp
描述：无限制GPT-3.5，免费国内大模型（阿里、腾讯、零一、360智脑、智谱、百川、月之暗面、讯飞、deepseek等）AI助手，部分模型自带支持联网，也可以使用联网插件实现联网资讯功能。新增开原模型llama2/3，meta/mistral，英伟达，以及huggingface里其他开原模型。新增逆转的国内大模型API，支持高速流式输出、支持多轮对话、支持智能体对话、支持AI绘图、支持长文档解读、图像解析等。

**Comment by xx025** [comment]
已更新
