### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by jwai4789** [xx025/carrot#861]
请提供以下内容：

- 标题: 3AM
- 链接：https://3am.com.hk
- 图标：https://3am.com.hk/favicon.ico
- 描述：註冊後完全免費無限制使用GPT3.5Turbo ， Claude3 Haiku ， Midjourney Relax模式，專注繁體中文AI 體驗
介面簡潔，支持微信/支付宝 國際信用卡；企業級騰訊雲香港服務器集群，服務SLA 可靠

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
