### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by luxlzz6** [xx025/carrot#867]
请提供以下内容：

- 标题: AI365
- 链接：https://chat.ai365vip.com/
- 图标：![bot](https://github.com/xx025/carrot/assets/53847251/b7f87428-f110-474a-ab7b-31c0436cfe01)
- 描述：打开即用 免费gpt-3.5 gpt4o和claude-3-haiku-20240307

**Comment by xx025** [comment]
已更新
