### ISSUE TITLE
ggwk

### ISSUE THREAD

**Issue by gg-game1** [xx025/carrot#868]
请提供以下内容：
- 标题: ggwk
- 链接：https://www.ggwk.online/
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：ggwkChat：高效快捷的api服务，包括Claude，GPT，gemini，GPTs全系列、gpt-4-all等官网主流模型，全面提升您的学习与工作效率。

**Comment by xx025** [comment]
已添加
