### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by dairoot** [xx025/carrot#869]
请提供以下内容：

- 标题：ChatGPT 镜像
- 链接：https://chatgpt.dairoot.cn/
- 图标：https://chatgpt.dairoot.cn/fe/favicon.png
- 描述：ChatGPT 官方 1:1 镜像

<img width="350" alt="image" src="https://github.com/xx025/carrot/assets/10009878/d053d486-8cd7-4095-bd94-1e871be41f54">

**Comment by xx025** [comment]
已添加
