### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by huchunyi** [xx025/carrot#870]
请提供以下内容：

- 标题: 毕方AI助手
- 链接：https://www.bfbke.com/chatgpt
- 图标：https://www.bfbke.com/favicon.ico
- 描述：登录后永久免费使用GPT4

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
