### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by kldhsh123** [xx025/carrot#873]
请提供以下内容：

- 标题:  我的AI
- 链接：https://myai.asia/
- 图标：https://img.picui.cn/free/2024/07/09/668c349c3eab4.jpg
- 描述：致力于公益项目，免登录无限制完全免费ChatGPT4和不同大厂的大模型。

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
