### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by bylvlv** [xx025/carrot#875]
请提供以下内容：

- 标题: 免费Claude 3.5 Sonnet
- 链接：https://claude.free2gpt.xyz
- 图标：https://pub-e66c6227d8704b26b6132ec1088917a9.r2.dev/lightapp/1719237398511.png
- 描述：无需注册登录，国内可用，限120次/天

**Comment by xx025** [comment]
已更新

**Comment by bylvlv** [comment]
> 已更新

@xx025 首页上看到的链接不对，应该是https://claude.free2gpt.xyz，写成了https://chatz.free2gpt.xyz（这个是
llama3-70b模型，也是免費的）

**Comment by xx025** [comment]
已更新
