### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by sushushu** [xx025/carrot#876]
请提供以下内容：

- 标题: 叔叔AI
- 链接：https://ssgpt.chat/home
- 图标：https://ssgpt.chat/avatar/static/avatar_1.jpg
- 描述：注册3.5免费，14块包月用GPT4o

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
