### ISSUE TITLE
HammerAI公益站

### ISSUE THREAD

**Issue by struggler2020** [xx025/carrot#881]
请提供以下内容：

- 标题: 
- 链接：
- 图标：
- 描述：

如

- 标题: HammerAI
- 链接：https://hammerai.pro
- 图标：https://hammerai.pro/wp-content/uploads/2024/07/cropped-f3c8e9cd888486db004c55d3f909df9-192x192.jpg
- 描述：⭐ 欢迎体验与使用HammerAI公益站，这是一款ChatGPT官网镜像站，1比1还原官网所有功能。不限次数使用 GPT-4 / GPT-4o / GPT-4omini模型！支持全态模型：支持语音对话、上传PDF、上传图片分析、上传文件分析。支持所有GPTs、Plugin插件，支持DALL·E-3模型！

**Comment by xx025** [comment]
已添加
