### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by Hafoxk** [xx025/carrot#884]
请提供以下内容：

- 标题: 极境智能
- 链接：https://www.gptnet.org
- 图标：https://oss.omair.org/AI/logo/logo-6.svg
- 描述：极境智能是一款集成多个先进模型的智能助手站，长期免费开放大个模型免费使用。

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已添加
