### ISSUE TITLE
AI导航星：1万+ AI工具，200+分类

### ISSUE THREAD

**Issue by Tavely** [xx025/carrot#887]
标题: AI导航星
链接：https://www.usbot.net/
图标：https://www.usbot.net/favicon.ico
描述：1万+ AI工具，200+分类，日常及专业需要
-------------------------------
你好，上次提交过，但是 没有看到，添加在哪里，麻烦再确认下，谢谢。

_Originally posted by @xx025 in https://github.com/xx025/carrot/issues/885#issuecomment-2273834722_

**Comment by xx025** [comment]
已更新，可能是之前检查没打开就隐藏了
