### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by girlisly** [xx025/carrot#888]
请提供以下内容：

- 标题: robot AI
- 链接：https://robotai.liujiarong.top
- 图标：https://robotai.liujiarong.top/icons/icon-192x192.png
- 描述：OpenAI: GPT-4-mini, GPT-4, GPT-4 Vision...
              Google: Gemini Pro, Gemini Vision...
              Anthropic: Claude, Claude 2.1...
              百度: 文心一言, ERNIE...
              阿里: 通义千问...
              腾讯: 混元...
              字节:豆包...
              以及众多开源大语言模型！
              登录后多端同步

**Comment by xx025** [comment]
站点已存在 https://chatnio.liujiarong.top -> https://robotai.liujiarong.top/
