### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by onlyGuo** [xx025/carrot#892]
请提供以下内容：

- 标题: Lite-GPT
- 链接：https://lite.icoding.ink/
- 图标：https://lite.icoding.ink/resources/icon.svg
- 描述：Lite-GPT is a free ChatGPT mirror site that integrates the latest models such as GPT-4o, Claude3, and Gemini, and supports various plugins.

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已更新

**Comment by xx025** [comment]
![image](https://github.com/user-attachments/assets/8c155bc6-858d-4c83-876f-6ab818f29f4f)

**Comment by onlyGuo** [comment]
是https://lite.icoding.ink/，而非https://free.icoding.ink/

**Comment by onlyGuo** [comment]
> ![image](https://private-user-images.githubusercontent.com/71559822/365257124-8c155bc6-858d-4c83-876f-6ab818f29f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTcwNjMsIm5iZiI6MTcyNTY5Njc2MywicGF0aCI6Ii83MTU1OTgyMi8zNjUyNTcxMjQtOGMxNTViYzYtODU4ZC00YzgzLTg3NmYtNmFiODE4ZjI5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA4MTI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMzRhODEzZWMxZTBjNGNkNzA5MjZkZDU5YWU5MWJjNzUyYWE0Mjk0OTdjM2I0MWI3ODZkZGY0ZTZmYTA4ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YCHrmzfjMjxI4WLJfXcsVBR4om2W4lrBlUzvLoMEKWo)

是lite.icoding.ink, 而非free.icoding.ink

**Comment by xx025** [comment]
已更新
