### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by easychats** [xx025/carrot#896]
- 标题: 免费ChatGPT-4、Claude 3.5 Sonnet
- 链接：https://easychat.fun/
- 图标：https://easychat.fun/favicon.svg
- 描述：免费gpt-4和claude3，无要注册登录，无付费渠道，可画图识文件，基础模型150次/天，部分模型50次/天（gpt-4-all），可用模型包括：openai系列，claude系列，Goolgle Gemini Pro, Meta开源模型

**Comment by xx025** [comment]
已添加
