### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by mxnf12** [xx025/carrot#899]
请提供以下内容：

- 标题: 
- 链接：
- 图标：
- 描述：

如

- 标题: ChatPro
- 链接：​https://g2.iswl.one
- 图标：https://fs-im-kefu.7moor-fs1.com/ly/4d2c3f00-7d4c-11e5-af15-41bf63ae4ea0/1725817981531/IMG_20240909_014656.png
- 描述：支持GPT4-to-mini的无限次免费使用，无需登录

**Comment by xx025** [comment]
已添加
