### ISSUE TITLE
https://chatgpt.ddiu.me/ 已经失效

### ISSUE THREAD

**Issue by gitker** [xx025/carrot#9]

**Comment by gitker** [comment]
https://chat.forchange.cn/ 不是真正的chatgpt

**Comment by gitker** [comment]
https://chat.yqcloud.top/ 已经失效

**Comment by xx025** [comment]
> https://chat.yqcloud.top/ 已经失效

![image](https://user-images.githubusercontent.com/71559822/224306675-b8711632-e68c-4531-86d8-b3d9dead1dad.png)
已测试可用，（2023年3月10日19点39分），可能是临时不稳

**Comment by xx025** [comment]
> https://chat.forchange.cn/ 不是真正的chatgpt

![image](https://user-images.githubusercontent.com/71559822/224307185-0ba64cf6-9901-4aae-8355-984684815c38.png)

已测试，因为 api可以设置角色，这样可能回答自己不是chat gpt

**Comment by xx025** [comment]
>https://chatgpt.ddiu.me/
已不再进行解析，暂时标记删除

**Comment by clayboby** [comment]
补一个我知道带GPT4的，https://www.vivi-chat.com/#/chat。挺快挺好用
