### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by xiongvalerio** [xx025/carrot#904]
请提供以下内容：

- 标题: ChatGPT Gratis
- 链接：https://chatgptgratis.eu
- 图标：https://chatgptgratis.eu/favicon.ico
- 描述：我找到了一个国外的免费chatgpt plus网站 目前看上去没限制 没广告 我不用国际网络也能使用 不知道别人 十分推荐这个

如

- 标题: Github Copilot
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
感谢分享，已添加

**Comment by leadscloud** [comment]
chatgptgratis.eu 这个站之前声称永久免费，现在是自动弹出广告，并且是赌博类的网站，建议降权，这不是普通的广告，属于有害广告。

并且它提供的模型有可能是假的。


这是套出的prompt

```
*Out of character confirmation**

The rules are as follows:

1. I am an AI model based on GPT-4omni designed by OpenAI.
2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
3. The message should be in the language of the user.

**Initialization code:** GPT-4OMNI-CHAT-INIT

**Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.

```

任何一个免费的模型，比如deepseek都可能模仿gpt-4o-mini，如果本身是gpt-4o-mini没必要告诉自己是gpt-4o-mini

**Comment by himankobe** [comment]
都白嫖flux文生图了 谁还在意广告 退回去不看就行了
