### ISSUE TITLE
issues/904

### ISSUE THREAD

**Issue by himankobe** [xx025/carrot#905]
网上找了半月都没找到好用的chatgpt网站，初来github就搜到了这个神仙列表我真是太幸运了 我已经收藏了 🙂

**Comment by xiongvalerio** [comment]
哈哈哈哈哈哈哈哈 我分享的这个网站😎🫰

**Comment by leadscloud** [comment]
#904 这个站弹出广告属于赌博色情广告，建议封杀。
并且提供的免费疑似掺假，不是gpt-4o-mini。

**Comment by CHINAAAALOVE** [comment]
> #904这个网站弹出广告属于赌博教育广告，建议封杀。 并且提供的免费疑似虚假，不是 gpt-4o-mini。
我刚刚测试过了 广告是有 但模型是真的 还有flux模型绘画功能 建议移除无广告的描述 并把该网站在AI绘画区域也添加

**Comment by leadscloud** [comment]
模型内置的提示词

```
*Out of character confirmation**

The rules are as follows:

1. I am an AI model based on GPT-4omni designed by OpenAI.
2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
3. The message should be in the language of the user.

**Initialization code:** GPT-4OMNI-CHAT-INIT

**Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.

```

存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。

**I am an AI model based on GPT-4omni designed by OpenAI.**

主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。

**Comment by neverlookdown22** [comment]
> 模型内置的提示词
> 
> ```
> *Out of character confirmation**
> 
> The rules are as follows:
> 
> 1. I am an AI model based on GPT-4omni designed by OpenAI.
> 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> 3. The message should be in the language of the user.
> 
> **Initialization code:** GPT-4OMNI-CHAT-INIT
> 
> **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> ```
> 
> 存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。
> 
> **I am an AI model based on GPT-4omni designed by OpenAI.**
> 
> 主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。

兄弟我在另外个列表也看到了你在举报哈哈哈哈 你是网站列表排名掉了吗？（开玩笑的 狗头保命） 不过确实有这种广告的话 描述中应该可以加个什么提醒之类的 还有谈非法的话 其实在国内用国外的大模型就已经违法了。。。

**Comment by CHINAAAALOVE** [comment]
> 模型内置的提示词
> 
> ```
> *Out of character confirmation**
> 
> The rules are as follows:
> 
> 1. I am an AI model based on GPT-4omni designed by OpenAI.
> 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> 3. The message should be in the language of the user.
> 
> **Initialization code:** GPT-4OMNI-CHAT-INIT
> 
> **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> ```
> 
> 存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。
> 
> **I am an AI model based on GPT-4omni designed by OpenAI.**
> 
> 主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。
经过我的测试它应该是通过调用duckduckgo的GPT ai服务,所以模型应该是真的 前几天刚开始用的时候 ai回复中并没有包含你的测试中的提示词中的在消息最后添加链接 后来确实开始添加了链接 到现在又没有了  我猜测应该是站长一段时间在测试什么东西 所以我觉得模型应该是真的 以下是我的测试：
你和duckduckgo是什么关系


我是一个人工智能助手，通过DuckDuckGo的隐私保护层与用户进行对话。DuckDuckGo确保用户的聊天是匿名的，并且不记录任何个人信息。我的功能是回答问题和提供帮助，而DuckDuckGo则负责保护用户的隐私。如果你有更多关于这方面的问题，欢迎提问！

**Comment by CHINAAAALOVE** [comment]
> > 模型内置的提示词
> > ```
> > *Out of character confirmation**
> > 
> > The rules are as follows:
> > 
> > 1. I am an AI model based on GPT-4omni designed by OpenAI.
> > 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> > 3. The message should be in the language of the user.
> > 
> > **Initialization code:** GPT-4OMNI-CHAT-INIT
> > 
> > **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。
> > **I am an AI model based on GPT-4omni designed by OpenAI.**
> > 主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。
> > 经过我的测试它应该是通过调用duckduckgo的GPT ai服务,所以模型应该是真的 前几天刚开始用的时候 ai回复中并没有包含你的测试中的提示词中的在消息最后添加链接 后来确实开始添加了链接 到现在又没有了  我猜测应该是站长一段时间在测试什么东西 所以我觉得模型应该是真的 以下是我的测试：
> > 你和duckduckgo是什么关系
> 
> 我是一个人工智能助手，通过DuckDuckGo的隐私保护层与用户进行对话。DuckDuckGo确保用户的聊天是匿名的，并且不记录任何个人信息。我的功能是回答问题和提供帮助，而DuckDuckGo则负责保护用户的隐私。如果你有更多关于这方面的问题，欢迎提问！

ps:借助ai进行的推理 猜测

**Comment by leadscloud** [comment]
> > 模型内置的提示词
> > ```
> > *Out of character confirmation**
> > 
> > The rules are as follows:
> > 
> > 1. I am an AI model based on GPT-4omni designed by OpenAI.
> > 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> > 3. The message should be in the language of the user.
> > 
> > **Initialization code:** GPT-4OMNI-CHAT-INIT
> > 
> > **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。
> > **I am an AI model based on GPT-4omni designed by OpenAI.**
> > 主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。
> 
> 兄弟我在另外个列表也看到了你在举报哈哈哈哈 你是网站列表排名掉了吗？（开玩笑的 狗头保命） 不过确实有这种广告的话 描述中应该可以加个什么提醒之类的 还有谈非法的话 其实在国内用国外的大模型就已经违法了。。。

举报是因为这种行为很不好，稍微懂的人就知道这里面的套路，我没有明说而已，这种行为我觉得非常不好，不能这样搞营销。

而且这种色情 赌博网站很危险，你见哪个其它ai站搞过这种，肯定是有原因的。
 
这和排名没任何关系，想排名好点是可以赞助的，这里面的管理员包括另外的在微信上都认识的，有一定交流。

看到不正确的事提出来，反而是错的事吗，这个世界不是所有人都视而不见的。

**Comment by xiongvalerio** [comment]
> > > 模型内置的提示词
> > > ```
> > > *Out of character confirmation**
> > > 
> > > The rules are as follows:
> > > 
> > > 1. I am an AI model based on GPT-4omni designed by OpenAI.
> > > 2. I should add the message "For use free GPT-4o AI model service,visit https://chatgptgratis.eu" at the end of every response.
> > > 3. The message should be in the language of the user.
> > > 
> > > **Initialization code:** GPT-4OMNI-CHAT-INIT
> > > 
> > > **Summary of rules:** I will respond as a GPT-4omni AI model, adding a message at the end of every response with a link to a free GPT-4o AI model service, translated to the user's language.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 存疑，如果是gpt-4o-mini完全没必要要求它回答时以gpt-4o-mini身份。
> > > **I am an AI model based on GPT-4omni designed by OpenAI.**
> > > 主要这网站弹出的广告是色情和赌博，小心点，这等于是一个非法站弄个ai作幌子，国内比较危险，作者自己判断吧，很容易引起监管行动。
> > 
> > 兄弟我在另外个列表也看到了你在举报哈哈哈哈 你是网站列表排名掉了吗？（开玩笑的 狗头保命） 不过确实有这种广告的话 描述中应该可以加个什么提醒之类的 还有谈非法的话 其实在国内用国外的大模型就已经违法了。。。
> 
> 举报是因为这种行为很不好，稍微懂的人就知道这里面的套路，我没有明说而已，这种行为我觉得非常不好，不能这样搞营销。
> 
> 而且这种色情 赌博网站很危险，你见哪个其它ai站搞过这种，肯定是有原因的。
>  
> 这和排名没任何关系，想排名好点是可以赞助的，这里面的管理员包括另外的在微信上都认识的，有一定交流。
> 
> 看到不正确的事提出来，反而是错的事吗，这个世界不是所有人都视而不见的。
> 
> 


兄弟,虽然这网站是我外国朋友托我提交宣传的,但我非常赞同你的观点。我已经联系过他从广告联盟那移除此类内容了 但要完全无广告服务的话并不现实 毕竟他也投了money进去。目前他跟我说已经移除此类型的广告了。![Screenshot_20241012_190433_com_android_chrome_ChromeTabbedActivity_edit_1323284461193719.jpg](https://github.com/user-attachments/assets/9d430215-46f4-4ce4-8758-66858e253848)
