### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by tangfeiepng** [xx025/carrot#915]
请提供以下内容：

- 标题: chatgpt和claude官方镜像站
- 链接：https://share.mynanian.top/
- 图标：
- 描述：注册即可免费试用的国内无需梯子的chatgpt

如

- 标题: Share Ai
- 链接：https://github.com/features/copilot
- 图标：https://github.com/images/modules/site/copilot/productivity-bg-head.png
- 描述：GitHub Copilot是一款基于AI的编程助手，提供智能代码补全。

**Comment by xx025** [comment]
已更新
