### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by opnoice** [xx025/carrot#917]
- 标题: NexusAI
- 链接：https://www.nexusapi.tech/
- 图标：https://raw.githubusercontent.com/NexusAILab/cdn/refs/heads/main/icon/logo.png
- 描述：NexusAI is your gateway to unlimited image generation and AI-powered chat experiences! We provide access to cutting-edge AI models like FLUX.1.1 [pro], FLUX.1 [pro], DALL-E-3, o1-preview, gpt-4o, and more – all for FREE! 🌎

**Comment by xx025** [comment]
https://www.nexusapi.tech/ -> https://www.nexusmind.tech/

**Comment by xx025** [comment]
已添加
