### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by mvfeng** [xx025/carrot#922]
请提供以下内容：

- 标题: 
- 链接：
- 图标：
- 描述：

如

- 标题:   ai导航-好导航94c
- 链接：https://hao.94c.cn
- 图标：https://hao.94c.cn/assets/images/favicon.png
- 描述：ai导航-好导航94c,chatgpt镜像,ai画画,免费ai工具集网站,你的ai助手,为你收集国内外aigc软件服务网址导航

**Comment by xx025** [comment]
已添加
