### ISSUE TITLE
添加站点: Yagc

### ISSUE THREAD

**Issue by imabutahersiddik** [xx025/carrot#923]
- **标题**: YAGC  
- **链接**: [https://yagc.tahriver.online](https://yagc.tahriver.online)  
- **图标**: [图标链接](https://yagc.tahriver.online/favicon.ico) *(请根据实际图标链接替换)*  
- **描述**: YAGC是一个动态的移动学习平台，提供多样化的教育资源，支持用户随时随地进行学习，促进灵活的教育方式。

**Comment by xx025** [comment]
已添加
