### ISSUE TITLE
添加站点: Free Temporary AI ChatBot 

### ISSUE THREAD

**Issue by imabutahersiddik** [xx025/carrot#924]
- **标题**: Temporary AI ChatBot 
- **链接**: [https://ftac.vercel.app](https://ftac.vercel.app)  
- **图标**: [图标链接](https://github.com/imabutahersiddik/Temporary-AI-ChatBot/blob/main/images/yachatbot_512.png) *(请根据实际图标链接替换)*  
- **描述**: Temporary AI ChatBot是一个免费的临时AI聊天机器人，旨在为用户提供即时的对话支持。它结合了先进的人工智能技术，允许用户随时随地与机器人互动，满足临时需求。通过简单易用的界面，YAGC为用户提供快速、灵活的解决方案，帮助他们在需要时获得所需的信息和支持。

**Comment by xx025** [comment]
已添加
