### ISSUE TITLE
添加站点

### ISSUE THREAD

**Issue by SericWong** [xx025/carrot#925]
请提供以下内容：

- 标题: AIBox-一站式AI工具平台
- 链接：https://chat.aibox365.cn
- 图标：https://chat.aibox365.cn/images/logo.png
- 描述：一站式AI工具平台，提供GPT4o、o1、Claude3.5、Gemini1.5等模型，支持Midjourney绘图、AIPPT等应用，每日提供免费使用额度。

**Comment by xx025** [comment]
已添加
